import { useState, useEffect, useContext } from 'react';
import { LanguageContext } from './LanguageContext';
import { AuthContext } from './AuthContext';
import axios from 'axios';

export const LanguageProvider = ({ children }) => {
  const { user } = useContext(AuthContext);
  const [language, setLanguageState] = useState(() => {
    return localStorage.getItem('sakhi_lang') || 'en';
  });

  // Sync state with localStorage
  useEffect(() => {
    localStorage.setItem('sakhi_lang', language);
  }, [language]);

  // Sync with backend on login
  useEffect(() => {
    const fetchLanguagePreference = async () => {
      if (user && user.token) {
        try {
          const res = await axios.get('http://localhost:5000/api/auth/preferences', {
            headers: { Authorization: `Bearer ${user.token}` },
          });
          if (res.data && res.data.language) {
            setLanguageState(res.data.language);
          }
        } catch (err) {
          console.error('Failed to fetch language preference:', err.message);
        }
      }
    };
    fetchLanguagePreference();
  }, [user]);

  const setLanguage = async (newLang) => {
    setLanguageState(newLang);
    if (user && user.token) {
      try {
        await axios.put(
          'http://localhost:5000/api/auth/preferences',
          { language: newLang },
          { headers: { Authorization: `Bearer ${user.token}` } }
        );
      } catch (err) {
        console.error('Failed to update language preference:', err.message);
      }
    }
  };

  const translations = {
    en: {
      browse: 'Browse',
      inbox: 'Inbox',
      dashboard: 'Dashboard',
      addProduct: 'Add Product',
      logout: 'Logout',
      login: 'Login',
      register: 'Register',
      searchPlaceholder: 'Search products, category, or sellers...',
      addToCart: 'Add to Cart',
      addedToCart: 'Added to Cart ✓',
      chatWithSeller: 'Chat with Seller',
      loginToChat: 'Login to Chat with Seller',
      shoppingCart: 'Shopping Cart',
      orderSummary: 'Order Summary',
      proceedToCheckout: 'Proceed to Checkout',
      paymentSuccess: 'Payment Successful!',
      accountSettings: 'Account Settings',
      purchaseHistory: 'Purchase History',
      savedItems: 'Saved Items',
      entrepreneurDetails: 'Entrepreneur Details',
      marketPriceGuideline: 'Market Price Guideline',
      productDescription: 'Product Description',
      marketPrices: 'Market Prices',
      editProfile: 'Edit Profile',
      saveChanges: 'Save Changes',
      cancel: 'Cancel',
      starRating: 'Star Rating',
      submitReview: 'Submit Review',
      vettingDashboard: 'Entrepreneur Vetting',
      productModeration: 'Product Vetting',
      platformOverview: 'Platform Overview',
      pendingApproval: 'Pending Approval',
      approved: 'Approved',
      suspended: 'Suspended',
      yourConversations: 'Your Conversations',
      yourOrders: 'Your Orders',
      securitySettings: 'Security & Password',
      currentPassword: 'Current Password',
      newPassword: 'New Password',
      confirmPassword: 'Confirm New Password',
      updatePassword: 'Update Password',
      profileUpdated: 'Profile updated successfully!',
      passwordUpdated: 'Password updated successfully!',
      passwordMismatch: 'New passwords do not match!',
      remove: 'Remove',
      emptyWishlist: 'Your Saved Items list is empty.',
      wishlistTitle: 'Your Saved Items',
      wishlistSubtitle: 'Build your perfect wishlist of hand-crafted items.',
      goFindFavorites: 'Go Find Favorites',
      languagePreference: 'Language Preference',
      buyerProfile: 'Buyer Profile',
      sellerProfile: 'Seller Profile',
      adminProfile: 'Admin Profile',
    },
    hi: {
      browse: 'खोजें',
      inbox: 'इनबॉक्स',
      dashboard: 'डैशबोर्ड',
      addProduct: 'उत्पाद जोड़ें',
      logout: 'लॉगआउट',
      login: 'लॉग इन',
      register: 'रजिस्टर',
      searchPlaceholder: 'उत्पाद, श्रेणी, या विक्रेता खोजें...',
      addToCart: 'कार्ट में जोड़ें',
      addedToCart: 'कार्ट में जोड़ा गया ✓',
      chatWithSeller: 'विक्रेता से बात करें',
      loginToChat: 'बात करने के लिए लॉग इन करें',
      shoppingCart: 'शॉपिंग कार्ट',
      orderSummary: 'ऑर्डर सारांश',
      proceedToCheckout: 'चेकआउट करें',
      paymentSuccess: 'भुगतान सफल रहा!',
      accountSettings: 'खाता सेटिंग्स',
      purchaseHistory: 'खरीद इतिहास',
      savedItems: 'पसंदीदा उत्पाद',
      entrepreneurDetails: 'उद्यमी का विवरण',
      marketPriceGuideline: 'बाजार मूल्य निर्देशिका',
      productDescription: 'उत्पाद विवरण',
      marketPrices: 'बाजार मूल्य',
      editProfile: 'प्रोफ़ाइल संपादित करें',
      saveChanges: 'परिवर्तन सहेजें',
      cancel: 'रद्द करें',
      starRating: 'स्टार रेटिंग',
      submitReview: 'समीक्षा जमा करें',
      vettingDashboard: 'उद्यमी समीक्षा',
      productModeration: 'उत्पाद समीक्षा',
      platformOverview: 'मंच अवलोकन',
      pendingApproval: 'अनुमोदन लंबित',
      approved: 'अनुमोदित',
      suspended: 'निलंबित',
      yourConversations: 'आपकी बातचीत',
      yourOrders: 'आपके ऑर्डर',
      securitySettings: 'सुरक्षा और पासवर्ड',
      currentPassword: 'वर्तमान पासवर्ड',
      newPassword: 'नया पासवर्ड',
      confirmPassword: 'नए पासवर्ड की पुष्टि करें',
      updatePassword: 'पासवर्ड अपडेट करें',
      profileUpdated: 'प्रोफ़ाइल सफलतापूर्वक अपडेट हो गई!',
      passwordUpdated: 'पासवर्ड सफलतापूर्वक अपडेट हो गया!',
      passwordMismatch: 'नए पासवर्ड मेल नहीं खाते!',
      remove: 'हटाएं',
      emptyWishlist: 'आपकी पसंदीदा उत्पाद सूची खाली है।',
      wishlistTitle: 'आपके पसंदीदा उत्पाद',
      wishlistSubtitle: 'हस्तनिर्मित वस्तुओं की अपनी पसंदीदा सूची बनाएं।',
      goFindFavorites: 'पसंदीदा उत्पाद खोजें',
      languagePreference: 'भाषा प्राथमिकता',
      buyerProfile: 'ग्राहक प्रोफ़ाइल',
      sellerProfile: 'विक्रेता प्रोफ़ाइल',
      adminProfile: 'प्रशासक प्रोफ़ाइल',
    },
    te: {
      browse: 'బ్రౌజ్ చేయండి',
      inbox: 'ఇన్‌బాక్స్',
      dashboard: 'డాష్‌బోర్డ్',
      addProduct: 'ఉత్పత్తిని జోడించు',
      logout: 'లాగ్ అవుట్',
      login: 'లాగిన్',
      register: 'నమోదు చేయండి',
      searchPlaceholder: 'ఉత్పత్తులు, వర్గం లేదా అమ్మకందారులను శోధించండి...',
      addToCart: 'కార్ట్‌కు జోడించు',
      addedToCart: 'కార్ట్‌కు జోడించబడింది ✓',
      chatWithSeller: 'విక్రేతతో చాట్ చేయండి',
      loginToChat: 'చాట్ చేయడానికి లాగిన్ అవ్వండి',
      shoppingCart: 'షాపింగ్ కార్ట్',
      orderSummary: 'ఆర్డర్ సారాంశం',
      proceedToCheckout: 'చెక్అవుట్ చేయండి',
      paymentSuccess: 'చెల్లింపు విజయవంతమైంది!',
      accountSettings: 'ఖాతా సెట్టింగులు',
      purchaseHistory: 'కొనుగోలు చరిత్ర',
      savedItems: 'ప్రియమైన ఉత్పత్తులు',
      entrepreneurDetails: 'కార్యకర్త వివరాలు',
      marketPriceGuideline: 'మార్కెట్ ధర మార్గదర్శిని',
      productDescription: 'ఉత్పత్తి వివరణ',
      marketPrices: 'మార్కెట్ ధరలు',
      editProfile: 'ప్రొఫైల్ సవరించండి',
      saveChanges: 'మార్పులను సేవ్ చేయి',
      cancel: 'రద్దు చేయి',
      starRating: 'నక్షత్ర రేటింగ్',
      submitReview: 'సమీక్షను సమర్పించండి',
      vettingDashboard: 'నిర్వాహక ధృవీకరణ',
      productModeration: 'ఉత్పత్తి తనిఖీ',
      platformOverview: 'ప్లాట్‌ఫారమ్ అవలోకనం',
      pendingApproval: 'ఆమోదం పెండింగ్‌లో ఉంది',
      approved: 'ఆమోదించబడింది',
      suspended: 'తాత్కాలికంగా నిలిపివేయబడింది',
      yourConversations: 'మీ సంభాషణలు',
      yourOrders: 'మీ ఆర్డర్లు',
      securitySettings: 'భద్రత & పాస్‌వర్డ్',
      currentPassword: 'ప్రస్తుత పాస్‌వర్డ్',
      newPassword: 'కొత్త పాస్‌వర్డ్',
      confirmPassword: 'కొత్త పాస్‌వర్డ్‌ను నిర్ధారించండి',
      updatePassword: 'పాస్‌వర్డ్‌ను నవీకరించండి',
      profileUpdated: 'ప్రొఫైల్ విజయవంతంగా నవీకరించబడింది!',
      passwordUpdated: 'పాస్‌వర్డ్ విజయవంతంగా నవీకరించబడింది!',
      passwordMismatch: 'కొత్త పాస్‌వర్డ్‌లు సరిపోలడం లేదు!',
      remove: 'తొలగించు',
      emptyWishlist: 'మీ ప్రియమైన ఉత్పత్తుల జాబితా ఖాళీగా ఉంది.',
      wishlistTitle: 'మీ ప్రియమైన ఉత్పత్తులు',
      wishlistSubtitle: 'హస్తకళల పరిపూర్ణమైన కోరికల జాబితాను రూపొందించుకోండి.',
      goFindFavorites: 'ఇష్టమైన ఉత్పత్తులను కనుగొనండి',
      languagePreference: 'భాష ప్రాధాన్యత',
      buyerProfile: 'కొనుగోలుదారు ప్రొఫైల్',
      sellerProfile: 'విక్రేత ప్రొఫైల్',
      adminProfile: 'అడ్మిన్ ప్రొఫైల్',
    },
    ta: {
      browse: 'உலாவு',
      inbox: 'இன்பாக்ஸ்',
      dashboard: 'டாஷ்போர்டு',
      addProduct: 'தயாரிப்பைச் சேர்',
      logout: 'வெளியேறு',
      login: 'உள்நுழைய',
      register: 'பதிவு செய்',
      searchPlaceholder: 'தயாரிப்புகள், வகை அல்லது விற்பனையாளர்களைத் தேடுக...',
      addToCart: 'வண்டியில் சேர்',
      addedToCart: 'வண்டியில் சேர்க்கப்பட்டது ✓',
      chatWithSeller: 'விற்பனையாளருடன் அரட்டையடி',
      loginToChat: 'அரட்டையடிக்க உள்நுழையவும்',
      shoppingCart: 'ஷாப்பிங் கார்ட்',
      orderSummary: 'ஆர்டர் சுருக்கம்',
      proceedToCheckout: 'செக்அவுட் செய்ய தொடரவும்',
      paymentSuccess: 'பணம் செலுத்துதல் வெற்றி!',
      accountSettings: 'கணக்கு அமைப்புகள்',
      purchaseHistory: 'கொள்முதல் வரலாறு',
      savedItems: 'சேமித்த பொருட்கள்',
      entrepreneurDetails: 'தொழில்முனைவோர் விவரங்கள்',
      marketPriceGuideline: 'சந்தை விலை வழிகாட்டி',
      productDescription: 'தயாரிப்பு விளக்கம்',
      marketPrices: 'சந்தை விலைகள்',
      editProfile: 'சுயவிவரத்தைத் திருத்து',
      saveChanges: 'மாற்றங்களைச் சேமிக்கவும்',
      cancel: 'ரத்துசெய்',
      starRating: 'நட்சத்திர மதிப்பீடு',
      submitReview: 'மதிப்பாய்வைச் சமர்ப்பி',
      vettingDashboard: 'தொழில்முனைவோர் சரிபார்ப்பு',
      productModeration: 'தயாரிப்பு மதிப்பாய்வு',
      platformOverview: 'தள கண்ணோட்டம்',
      pendingApproval: 'ஒப்புதல் நிலுவையில் உள்ளது',
      approved: 'அங்கீகரிக்கப்பட்டது',
      suspended: 'நிறுத்தி வைக்கப்பட்டது',
      yourConversations: 'உங்கள் உரையாடல்கள்',
      yourOrders: 'உங்கள் ஆர்டர்கள்',
      securitySettings: 'பாதுகாப்பு & கடவுச்சொல்',
      currentPassword: 'தற்போதைய கடவுச்சொல்',
      newPassword: 'புதிய கடவுச்சொல்',
      confirmPassword: 'புதிய கடவுச்சொல்லை உறுதிப்படுத்தவும்',
      updatePassword: 'கடவுச்சொல்லைப் புதுப்பிக்கவும்',
      profileUpdated: 'சுயவிவரம் வெற்றிகரமாக புதுப்பிக்கப்பட்டது!',
      passwordUpdated: 'கடவுச்சொல் வெற்றிகரமாக புதுப்பிக்கப்பட்டது!',
      passwordMismatch: 'புதிய கடவுச்சொற்கள் பொருந்தவில்லை!',
      remove: 'அகற்று',
      emptyWishlist: 'உங்கள் சேமித்த பொருட்கள் பட்டியல் காலியாக உள்ளது.',
      wishlistTitle: 'உங்கள் சேமித்த பொருட்கள்',
      wishlistSubtitle: 'கைவினைப் பொருட்களின் உங்களது சரியான விருப்பப்பட்டியலை உருவாக்குங்கள்.',
      goFindFavorites: 'விருப்பமானவற்றைக் கண்டறியவும்',
      languagePreference: 'மொழி முன்னுரிமை',
      buyerProfile: 'வாங்குபவர் சுயவிவரம்',
      sellerProfile: 'விற்பனையாளர் சுயவிவரம்',
      adminProfile: 'நிர்வாகி சுயவிவரம்',
    },
    kn: {
      browse: 'ಬ್ರೌಸ್ ಮಾಡಿ',
      inbox: 'ಇನ್‌ಬಾಕ್ಸ್',
      dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
      addProduct: 'ಉತ್ಪನ್ನ ಸೇರಿಸಿ',
      logout: 'ಲಾಗ್ ಔಟ್',
      login: 'ಲಾಗಿನ್',
      register: 'ನೋಂದಣಿ',
      searchPlaceholder: 'ಉತ್ಪನ್ನಗಳು, ವರ್ಗ ಅಥವಾ ಮಾರಾಟಗಾರರನ್ನು ಹುಡುಕಿ...',
      addToCart: 'ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಿ',
      addedToCart: 'ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಲಾಗಿದೆ ✓',
      chatWithSeller: 'ಮಾರಾಟಗಾರರೊಂದಿಗೆ ಚಾಟ್ ಮಾಡಿ',
      loginToChat: 'ಚಾಟ್ ಮಾಡಲು ಲಾಗಿನ್ ಮಾಡಿ',
      shoppingCart: 'ಶಾಪಿಂಗ್ ಕಾರ್ಟ್',
      orderSummary: 'ಆರ್ಡರ್ ಸಾರಾಂಶ',
      proceedToCheckout: 'ಚೆಕ್‌ಔಟ್‌ಗೆ ಮುಂದುವರಿಯಿರಿ',
      paymentSuccess: 'ಪಾವತಿ ಯಶಸ್ವಿಯಾಗಿದೆ!',
      accountSettings: 'ಖಾತೆ ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
      purchaseHistory: 'ಖರೀದಿ ಇತಿಹಾಸ',
      savedItems: 'ಉಳಿಸಿದ ವಸ್ತುಗಳು',
      entrepreneurDetails: 'ಉದ್ಯಮಿಗಳ ವಿವರಗಳು',
      marketPriceGuideline: 'ಮಾರುಕಟ್ಟೆ ಬೆಲೆ ಮಾರ್ಗದರ್ಶಿ',
      productDescription: 'ಉತ್ಪನ್ನ ವಿವರಣೆ',
      marketPrices: 'ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಳು',
      editProfile: 'ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ',
      saveChanges: 'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ',
      cancel: 'ರದ್ದುಗೊಳಿಸಿ',
      starRating: 'ಸ್ಟಾರ್ ರೇಟಿಂಗ್',
      submitReview: 'ವಿಮರ್ಶೆ ಸಲ್ಲಿಸಿ',
      vettingDashboard: 'ಉದ್ಯಮಿ ಪರಿಶೀಲನೆ',
      productModeration: 'ಉತ್ಪನ್ನ ಪರಿಶೀಲನೆ',
      platformOverview: 'ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಅವಲೋಕನ',
      pendingApproval: 'ಅನುಮೋದನೆ ಬಾಕಿ ಇದೆ',
      approved: 'ಅನುಮೋದಿಸಲಾಗಿದೆ',
      suspended: 'ಅಮಾನತುಗೊಳಿಸಲಾಗಿದೆ',
      yourConversations: 'ನಿಮ್ಮ ಸಂಭಾಷಣೆಗಳು',
      yourOrders: 'ನಿಮ್ಮ ಆರ್ಡರ್‌ಗಳು',
      securitySettings: 'ಭದ್ರತೆ ಮತ್ತು ಪಾಸ್‌ವರ್ಡ್',
      currentPassword: 'ಪ್ರಸ್ತುತ ಪಾಸ್‌ವರ್ಡ್',
      newPassword: 'ಹೊಸ ಪಾಸ್‌ವರ್ಡ್',
      confirmPassword: 'ಹೊಸ ಪಾಸ್‌ವರ್ಡ್ ಖಚಿತಪಡಿಸಿ',
      updatePassword: 'ಪಾಸ್‌ವರ್ಡ್ ನವೀಕರಿಸಿ',
      profileUpdated: 'ಪ್ರೊಫೈಲ್ ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ!',
      passwordUpdated: 'ಪಾಸ್‌ವರ್ಡ್ ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ!',
      passwordMismatch: 'ಹೊಸ ಪಾಸ್‌ವರ್ಡ್‌ಗಳು ಹೊಂದಿಕೆಯಾಗುತ್ತಿಲ್ಲ!',
      remove: 'ತೆಗೆದುಹಾಕಿ',
      emptyWishlist: 'ನಿಮ್ಮ ಉಳಿಸಿದ ವಸ್ತುಗಳ ಪಟ್ಟಿ ಖಾಲಿ ಇದೆ.',
      wishlistTitle: 'ನಿಮ್ಮ ಉಳಿಸಿದ ವಸ್ತುಗಳು',
      wishlistSubtitle: 'ಹಸ್ತಕಲಾ ವಸ್ತುಗಳ ನಿಮ್ಮ ಪರಿಪೂರ್ಣ ಇಷ್ಟದ ಪಟ್ಟಿಯನ್ನು ನಿರ್ಮಿಸಿ.',
      goFindFavorites: 'ಮೆಚ್ಚಿನವುಗಳನ್ನು ಹುಡುಕಿ',
      languagePreference: 'ಭಾಷೆಯ ಆದ್ಯತೆ',
      buyerProfile: 'ಖರೀದಿದಾರರ ಪ್ರೊಫೈಲ್',
      sellerProfile: 'ಮಾರಾಟಗಾರರ ಪ್ರೊಫೈಲ್',
      adminProfile: 'ಅಡ್ಮಿನ್ ಪ್ರೊಫೈಲ್',
    },
    ml: {
      browse: 'ബ്രൗസ് ചെയ്യുക',
      inbox: 'ഇൻബോക്സ്',
      dashboard: 'ഡാഷ്‌ബോർഡ്',
      addProduct: 'ഉൽപ്പന്നം ചേർക്കുക',
      logout: 'ലോഗ് ഔട്ട്',
      login: 'ലോഗിൻ',
      register: 'രജിസ്റ്റർ ചെയ്യുക',
      searchPlaceholder: 'ഉൽപ്പന്നങ്ങൾ, വിഭാഗം അല്ലെങ്കിൽ വിൽപ്പനക്കാരെ തിരയുക...',
      addToCart: 'കാർട്ടിലേക്ക് ചേർക്കുക',
      addedToCart: 'കാർട്ടിൽ ചേർത്തു ✓',
      chatWithSeller: 'വിൽപ്പനക്കാരനുമായി ചാറ്റ് ചെയ്യുക',
      loginToChat: 'ചാറ്റ് ചെയ്യാൻ ലോഗിൻ ചെയ്യുക',
      shoppingCart: 'ഷോപ്പിംഗ് കാർട്ട്',
      orderSummary: 'ഓർഡർ സംഗ്രഹം',
      proceedToCheckout: 'ചെക്ക്ഔട്ടിലേക്ക് പോകുക',
      paymentSuccess: 'പേയ്‌മെന്റ് വിജയകരമായി!',
      accountSettings: 'അക്കൗണ്ട് ക്രമീകരണങ്ങൾ',
      purchaseHistory: 'വാങ്ങൽ ചരിത്രം',
      savedItems: 'സംരക്ഷിച്ചവ',
      entrepreneurDetails: 'സംരംഭകരുടെ വിവരങ്ങൾ',
      marketPriceGuideline: 'മാർക്കറ്റ് വില വിവരങ്ങൾ',
      productDescription: 'ഉൽപ്പന്ന വിവരണം',
      marketPrices: 'മാർക്കറ്റ് വിലകൾ',
      editProfile: 'പ്രൊഫൈൽ എഡിറ്റ് ചെയ്യുക',
      saveChanges: 'മാറ്റങ്ങൾ സംരക്ഷിക്കുക',
      cancel: 'റദ്ദാക്കുക',
      starRating: 'സ്റ്റാർ റേറ്റിംഗ്',
      submitReview: 'അഭിപ്രായം രേഖപ്പെടുത്തുക',
      vettingDashboard: 'സംരംഭക പരിശോധന',
      productModeration: 'ഉൽപ്പന്ന പരിശോധന',
      platformOverview: 'പ്ലാറ്റ്ഫോം അവലോകനം',
      pendingApproval: 'അംഗീകാരം ലഭിക്കാനുണ്ട്',
      approved: 'അംഗീകരിച്ചു',
      suspended: 'സസ്പെൻഡ് ചെയ്തു',
      yourConversations: 'നിങ്ങളുടെ സംഭാഷണങ്ങൾ',
      yourOrders: 'നിങ്ങളുടെ ഓർഡറുകൾ',
      securitySettings: 'സുരക്ഷയും പാസ്‌വേഡും',
      currentPassword: 'നിലവിലെ പാസ്‌വേഡ്',
      newPassword: 'പുതിയ പാസ്‌വേഡ്',
      confirmPassword: 'പുതിയ പാസ്‌വേഡ് സ്ഥിരീകരിക്കുക',
      updatePassword: 'പാസ്‌വേഡ് അപ്‌ഡേറ്റ് ചെയ്യുക',
      profileUpdated: 'പ്രൊഫൈൽ വിജയകരമായി അപ്‌ഡേറ്റ് ചെയ്തു!',
      passwordUpdated: 'പാസ്‌വേഡ് വിജയകരമായി അപ്‌ഡേറ്റ് ചെയ്തു!',
      passwordMismatch: 'പുതിയ പാസ്‌വേഡുകൾ പൊരുത്തപ്പെടുന്നില്ല!',
      remove: 'ഒഴിവാക്കുക',
      emptyWishlist: 'നിങ്ങൾ സംരക്ഷിച്ച ഇനങ്ങൾ ഒന്നുമില്ല.',
      wishlistTitle: 'നിങ്ങൾ സംരക്ഷിച്ചവ',
      wishlistSubtitle: 'നിങ്ങളുടെ മികച്ച ഇഷ്ടാനിഷ്ടങ്ങളുടെ ലിസ്റ്റ് തയ്യാറാക്കുക.',
      goFindFavorites: 'ഇഷ്ടപ്പെട്ടവ കണ്ടെത്തുക',
      languagePreference: 'ഭാഷാ മുൻഗണന',
      buyerProfile: 'വാങ്ങുന്നയാളുടെ പ്രൊഫൈൽ',
      sellerProfile: 'വിൽപ്പനക്കാരന്റെ പ്രൊഫൈൽ',
      adminProfile: 'അഡ്മിൻ പ്രൊഫൈൽ',
    },
    mr: {
      browse: 'शोध घ्या',
      inbox: 'इन्बॉक्स',
      dashboard: 'डॅशबोर्ड',
      addProduct: 'उत्पादन जोडा',
      logout: 'लॉगआउट',
      login: 'लॉगिन',
      register: 'नोंदणी करा',
      searchPlaceholder: 'उत्पादने, श्रेणी किंवा विक्रेते शोधा...',
      addToCart: 'कार्टमध्ये जोडा',
      addedToCart: 'कार्टमध्ये जोडले गेले ✓',
      chatWithSeller: 'विक्रेत्याशी चॅट करा',
      loginToChat: 'चॅट करण्यासाठी लॉगिन करा',
      shoppingCart: 'शॉपिंग कार्ट',
      orderSummary: 'ऑर्डरचा सारांश',
      proceedToCheckout: 'चेकआऊट करा',
      paymentSuccess: 'पेमेंट यशस्वी झाले!',
      accountSettings: 'खाते सेटिंग्ज',
      purchaseHistory: 'खरेदीचा इतिहास',
      savedItems: 'जतन केलेल्या वस्तू',
      entrepreneurDetails: 'उद्योजिकेचा तपशील',
      marketPriceGuideline: 'बाजार भाव मार्गदर्शिका',
      productDescription: 'उत्पादन वर्णन',
      marketPrices: 'बाजार भाव',
      editProfile: 'प्रोफाईल संपादित करा',
      saveChanges: 'बदल जतन करा',
      cancel: 'रद्द करा',
      starRating: 'स्टार रेटिंग',
      submitReview: 'पुनरावलोकन सबमिट करा',
      vettingDashboard: 'उद्योजिका पडताळणी',
      productModeration: 'उत्पादन पडताळणी',
      platformOverview: 'प्लॅटफॉर्म विहंगावलोकन',
      pendingApproval: 'मंजुरी प्रलंबित',
      approved: 'मंजूर',
      suspended: 'निलंबित',
      yourConversations: 'तुमचे संभाषण',
      yourOrders: 'तुमच्या ऑर्डर्स',
      securitySettings: 'सुरक्षा आणि पासवर्ड',
      currentPassword: 'सध्याचा पासवर्ड',
      newPassword: 'नवीन पासवर्ड',
      confirmPassword: 'नवीन पासवर्डची पुष्टी करा',
      updatePassword: 'पासवर्ड अपडेट करा',
      profileUpdated: 'प्रोफाईल यशस्वीरित्या अपडेट झाली!',
      passwordUpdated: 'पासवर्ड यशस्वीरित्या अपडेट झाला!',
      passwordMismatch: 'नवीन पासवर्ड जुळत नाहीत!',
      remove: 'काढून टाका',
      emptyWishlist: 'तुमची जतन केलेल्या वस्तूंची यादी रिकामी आहे.',
      wishlistTitle: 'तुमच्या जतन केलेल्या वस्तू',
      wishlistSubtitle: 'हस्तनिर्मित वस्तूंची तुमची आवडती यादी तयार करा.',
      goFindFavorites: 'आवडत्या वस्तू शोधा',
      languagePreference: 'भाषा प्राधान्य',
      buyerProfile: 'ग्राहक प्रोफाईल',
      sellerProfile: 'विक्रेता प्रोफाईल',
      adminProfile: 'प्रशासक प्रोफाईल',
    },
    bn: {
      browse: 'খুঁজুন',
      inbox: 'ইনবক্স',
      dashboard: 'ড্যাশবোর্ড',
      addProduct: 'পণ্য যোগ করুন',
      logout: 'লগআউট',
      login: 'লগইন',
      register: 'রেজিস্টার',
      searchPlaceholder: 'পণ্য, বিভাগ বা বিক্রেতা খুঁজুন...',
      addToCart: 'কার্টে যোগ করুন',
      addedToCart: 'কার্টে যোগ করা হয়েছে ✓',
      chatWithSeller: 'বিক্রেতার সাথে চ্যাট করুন',
      loginToChat: 'চ্যাট করতে লগইন করুন',
      shoppingCart: 'শপিং কার্ট',
      orderSummary: 'অর্ডারের বিবরণ',
      proceedToCheckout: 'চেকআউটে যান',
      paymentSuccess: 'পেমেন্ট সফল হয়েছে!',
      accountSettings: 'অ্যাকাউন্ট সেটিংস',
      purchaseHistory: 'ক্রয় ইতিহাস',
      savedItems: 'পছন্দের তালিকা',
      entrepreneurDetails: 'উদ্যোক্তার বিবরণ',
      marketPriceGuideline: 'বাজার মূল্য নির্দেশিকা',
      productDescription: 'পণ্যের বিবরণ',
      marketPrices: 'বাজার মূল্য',
      editProfile: 'প্রোফাইল সম্পাদনা',
      saveChanges: 'পরিবর্তন সংরক্ষণ',
      cancel: 'বাতিল',
      starRating: 'স্টার রেটিং',
      submitReview: 'রিভিউ দিন',
      vettingDashboard: 'উদ্যোক্তা যাচাইকরণ',
      productModeration: 'পণ্য যাচাইকরণ',
      platformOverview: 'প্ল্যাটফর্মের বিবরণ',
      pendingApproval: 'অনুমোদন পেন্ডিং',
      approved: 'অনুমোদিত',
      suspended: 'স্থগিত',
      yourConversations: 'আপনার চ্যাটসমূহ',
      yourOrders: 'আপনার অর্ডারসমূহ',
      securitySettings: 'সুরক্ষা এবং পাসওয়ার্ড',
      currentPassword: 'বর্তমান পাসওয়ার্ড',
      newPassword: 'নতুন পাসওয়ার্ড',
      confirmPassword: 'নতুন পাসওয়ার্ড নিশ্চিত করুন',
      updatePassword: 'পাসওয়ার্ড আপডেট করুন',
      profileUpdated: 'প্রোফাইল সফলভাবে আপডেট করা হয়েছে!',
      passwordUpdated: 'পাসওয়ার্ড সফলভাবে আপডেট করা হয়েছে!',
      passwordMismatch: 'নতুন পাসওয়ার্ড মেলেনি!',
      remove: 'মুছুন',
      emptyWishlist: 'আপনার পছন্দের তালিকা খালি।',
      wishlistTitle: 'আপনার পছন্দের পণ্যসমূহ',
      wishlistSubtitle: 'হস্তশিল্প পণ্যের নিজস্ব পছন্দের তালিকা তৈরি করুন।',
      goFindFavorites: 'পছন্দের পণ্য খুঁজুন',
      languagePreference: 'ভাষা পছন্দ',
      buyerProfile: 'ক্রেতার প্রোফাইল',
      sellerProfile: 'বিক্রেতার প্রোফাইল',
      adminProfile: 'অ্যাডমিন প্রোফাইল',
    },
    gu: {
      browse: 'શોધો',
      inbox: 'ઇનબોક્સ',
      dashboard: 'ડેશબોર્ડ',
      addProduct: 'ઉત્પાદન ઉમેરો',
      logout: 'લોગઆઉટ',
      login: 'લોગિન',
      register: 'રજીસ્ટર કરો',
      searchPlaceholder: 'ઉત્પાદન, શ્રેણી અથવા વિક્રેતા શોધો...',
      addToCart: 'કાર્ટમાં ઉમેરો',
      addedToCart: 'કાર્ટમાં ઉમેરાયું ✓',
      chatWithSeller: 'વિક્રેતા સાથે ચેટ કરો',
      loginToChat: 'ચેટ કરવા લોગિન કરો',
      shoppingCart: 'શોપિંગ કાર્ટ',
      orderSummary: 'ઓર્ડર સારાંશ',
      proceedToCheckout: 'ચેકઆઉટ કરો',
      paymentSuccess: 'ચુકવણી સફળ રહી!',
      accountSettings: 'ખાતા સેટિંગ્સ',
      purchaseHistory: 'ખરીદીનો ઇતિહાસ',
      savedItems: 'પસંદગીની વસ્તુઓ',
      entrepreneurDetails: 'ઉદ્યોગસાહસિક વિગતો',
      marketPriceGuideline: 'બજાર ભાવ માર્ગદર્શિકા',
      productDescription: 'ઉત્પાદન વર્ણન',
      marketPrices: 'બજાર ભાવો',
      editProfile: 'પ્રોફાઇલ સંપાદિત કરો',
      saveChanges: 'ફેરફારો સાચવો',
      cancel: 'રદ કરો',
      starRating: 'સ્ટાર રેટિંગ',
      submitReview: 'સમીક્ષા સબમિટ કરો',
      vettingDashboard: 'ઉદ્યોગસાહસિક ચકાસણી',
      productModeration: 'ઉત્પાદન ચકાસણી',
      platformOverview: 'પ્લેટફોર્મ વિહંગાવલોકન',
      pendingApproval: 'મંજૂરી બાકી છે',
      approved: 'મંજૂર',
      suspended: 'સ્થગિત',
      yourConversations: 'તમારી વાતચીત',
      yourOrders: 'તમારા ઓર્ડર્સ',
      securitySettings: 'સુરક્ષા અને પાસવર્ડ',
      currentPassword: 'વર્તમાન પાસવર્ડ',
      newPassword: 'નવો પાસવર્ડ',
      confirmPassword: 'નવા પાસવર્ડની પુષ્ટિ કરો',
      updatePassword: 'પાસવર્ડ અપડેટ કરો',
      profileUpdated: 'પ્રોફાઇલ સફળતાપૂર્વક અપડેટ થઈ!',
      passwordUpdated: 'પાસવર્ડ સફળતાપૂર્વક અપડેટ થયો!',
      passwordMismatch: 'નવા પાસવર્ડ મેળ ખાતા નથી!',
      remove: 'દૂર કરો',
      emptyWishlist: 'તમારી પસંદગીની વસ્તુઓની યાદી ખાલી છે.',
      wishlistTitle: 'તમારી પસંદગીની વસ્તુઓ',
      wishlistSubtitle: 'હસ્તકલા વસ્તુઓની તમારી આદર્શ વિશલિસ્ટ બનાવો.',
      goFindFavorites: 'પસંદગીની વસ્તુઓ શોધો',
      languagePreference: 'ભાષા પસંદગી',
      buyerProfile: 'ગ્રાહક પ્રોફાઇલ',
      sellerProfile: 'વિક્રેતા પ્રોફાઇલ',
      adminProfile: 'એડમિન પ્રોફાઇલ',
    },
    pa: {
      browse: 'ਖੋਜੋ',
      inbox: 'ਇਨਬਾਕਸ',
      dashboard: 'ਡੈਸ਼ਬੋਰਡ',
      addProduct: 'ਉਤਪਾਦ ਜੋੜੋ',
      logout: 'ਲੌਗਆਊਟ',
      login: 'ਲੌਗਇਨ',
      register: 'ਰਜਿਸਟਰ ਕਰੋ',
      searchPlaceholder: 'ਉਤਪਾਦ, ਸ਼੍ਰੇਣੀ ਜਾਂ ਵਿਕਰੇਤਾ ਖੋਜੋ...',
      addToCart: 'ਕਾਰਟ ਵਿੱਚ ਜੋੜੋ',
      addedToCart: 'ਕਾਰਟ ਵਿੱਚ ਜੋੜਿਆ ਗਿਆ ✓',
      chatWithSeller: 'ਵਿਕਰੇਤਾ ਨਾਲ ਗੱਲਬਾਤ ਕਰੋ',
      loginToChat: 'ਗੱਲਬਾਤ ਲਈ ਲੌਗਇਨ ਕਰੋ',
      shoppingCart: 'ਸ਼ਾਪਿੰਗ ਕਾਰਟ',
      orderSummary: 'ਆਰਡਰ ਸਾਰਾਂਸ਼',
      proceedToCheckout: 'ਚੈੱਕਆਊਟ ਕਰੋ',
      paymentSuccess: 'ਭੁਗਤਾਨ ਸਫਲ ਰਿਹਾ!',
      accountSettings: 'ਖਾਤਾ ਸੈਟਿੰਗਜ਼',
      purchaseHistory: 'ਖਰੀਦ ਇਤਿਹਾਸ',
      savedItems: 'ਪਸੰਦੀਦਾ ਉਤਪਾਦ',
      entrepreneurDetails: 'ਉੱਦਮੀ ਦੇ ਵੇਰਵੇ',
      marketPriceGuideline: 'ਬਾਜ਼ਾਰ ਕੀਮਤ ਨਿਰਦੇਸ਼ਿਕਾ',
      productDescription: 'ਉਤਪਾਦ ਵੇਰਵਾ',
      marketPrices: 'ਬਾਜ਼ਾਰ ਕੀਮਤਾਂ',
      editProfile: 'ਪ੍ਰੋਫਾਈਲ ਸੋਧੋ',
      saveChanges: 'ਤਬਦੀਲੀਆਂ ਸੁਰੱਖਿਅਤ ਕਰੋ',
      cancel: 'ਰੱਦ ਕਰੋ',
      starRating: 'ਸਟਾਰ ਰੇਟਿੰਗ',
      submitReview: 'ਸਮੀਖਿਆ ਦਰਜ ਕਰੋ',
      vettingDashboard: 'ਉੱਦਮੀ ਸਮੀਖਿਆ',
      productModeration: 'ਉਤਪਾਦ ਸਮੀਖਿਆ',
      platformOverview: 'ਮੰਚ ਅਵਲੋਕਨ',
      pendingApproval: 'ਮਨਜ਼ੂਰੀ ਲੰਬਿਤ',
      approved: 'ਮਨਜ਼ੂਰਸ਼ੁਦਾ',
      suspended: 'ਮੁਅੱਤਲ',
      yourConversations: 'ਤੁਹਾਡੀਆਂ ਗੱਲਬਾਤਾਂ',
      yourOrders: 'ਤੁਹਾਡੇ ਆਰਡਰ',
      securitySettings: 'ਸੁਰੱਖਿਆ ਅਤੇ ਪਾਸਵਰਡ',
      currentPassword: 'ਮੌਜੂਦਾ ਪਾਸਵਰਡ',
      newPassword: 'ਨਵਾਂ ਪਾਸਵਰਡ',
      confirmPassword: 'ਨਵੇਂ ਪਾਸਵਰਡ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
      updatePassword: 'ਪਾਸਵਰਡ ਅੱਪਡੇਟ ਕਰੋ',
      profileUpdated: 'ਪ੍ਰੋਫਾਈਲ ਸਫਲਤਾਪੂਰਵਕ ਅੱਪਡੇਟ ਹੋ ਗਈ!',
      passwordUpdated: 'ਪਾਸਵਰਡ ਸਫਲਤਾਪੂਰਵਕ ਅੱਪਡੇਟ ਹੋ ਗਿਆ!',
      passwordMismatch: 'ਨਵੇਂ ਪਾਸਵਰਡ ਮੇਲ ਨਹੀਂ ਖਾਂਦੇ!',
      remove: 'ਹਟਾਓ',
      emptyWishlist: 'ਤੁਹਾਡੀ ਪਸੰਦੀਦਾ ਉਤਪਾਦ ਸੂਚੀ ਖਾਲੀ ਹੈ।',
      wishlistTitle: 'ਤੁਹਾਡੇ ਪਸੰਦੀਦਾ ਉਤਪਾਦ',
      wishlistSubtitle: 'ਹਸਤਕਲਾ ਵਸਤੂਆਂ ਦੀ ਆਪਣੀ ਆਦਰਸ਼ ਸੂਚੀ ਬਣਾਓ।',
      goFindFavorites: 'ਪਸੰਦੀਦਾ ਉਤਪਾਦ ਲੱਭੋ',
      languagePreference: 'ਭਾਸ਼ਾ ਤਰਜੀਹ',
      buyerProfile: 'ਖਰੀਦਦਾਰ ਪ੍ਰੋਫਾਈਲ',
      sellerProfile: 'ਵਿਕਰੇਤਾ ਪ੍ਰੋਫਾਈਲ',
      adminProfile: 'ਐਡਮਿਨ ਪ੍ਰੋਫਾਈਲ',
    },
  };

  const t = (key) => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export default LanguageProvider;
