import { useState, useEffect, useContext } from 'react';
import { LanguageContext } from './LanguageContext';
import { AuthContext } from './AuthContext';
import axios from 'axios';

export const LanguageProvider = ({ children }) => {
  const { user } = useContext(AuthContext);
  const [language, setLanguageState] = useState(() => {
    return localStorage.getItem('sakhi_lang') || 'en';
  });

  // Sync state with localStorage
  useEffect(() => {
    localStorage.setItem('sakhi_lang', language);
  }, [language]);

  // Sync with backend preference if logged in
  useEffect(() => {
    const fetchLanguagePreference = async () => {
      if (user && user.token) {
        try {
          const res = await axios.get('http://localhost:5000/api/auth/preferences', {
            headers: { Authorization: `Bearer ${user.token}` },
          });
          if (res.data && res.data.language) {
            setLanguageState(res.data.language);
          }
        } catch (err) {
          console.error('Failed to fetch language preference:', err.message);
        }
      }
    };
    fetchLanguagePreference();
  }, [user]);

  const setLanguage = async (newLang) => {
    setLanguageState(newLang);
    if (user && user.token) {
      try {
        await axios.put(
          'http://localhost:5000/api/auth/preferences',
          { language: newLang },
          { headers: { Authorization: `Bearer ${user.token}` } }
        );
      } catch (err) {
        console.error('Failed to update language preference:', err.message);
      }
    }
  };

  const translations = {
    en: {
      browse: 'Browse',
      inbox: 'Inbox',
      dashboard: 'Dashboard',
      addProduct: 'Add Product',
      addNewProduct: 'Add New Product',
      logout: 'Logout',
      login: 'Login',
      register: 'Register',
      searchPlaceholder: 'Search products, category, or sellers...',
      addToCart: 'Add to Cart',
      addedToCart: 'Added to Cart ✓',
      buyNow: 'Buy Now',
      chatWithSeller: 'Chat with Seller',
      loginToChat: 'Login to Chat with Seller',
      shoppingCart: 'Shopping Cart',
      cart: 'Cart',
      orderSummary: 'Order Summary',
      proceedToCheckout: 'Proceed to Checkout',
      paymentSuccess: 'Payment Successful!',
      accountSettings: 'Account Settings',
      purchaseHistory: 'Purchase History',
      savedItems: 'Saved Items',
      entrepreneurDetails: 'Entrepreneur Details',
      marketPriceGuideline: 'Market Price Guideline',
      productDescription: 'Product Description',
      marketPrices: 'Market Prices',
      editProfile: 'Edit Profile',
      saveChanges: 'Save Changes',
      cancel: 'Cancel',
      starRating: 'Star Rating',
      submitReview: 'Submit Review',
      vettingDashboard: 'Entrepreneur Vetting',
      productModeration: 'Product Vetting',
      platformOverview: 'Platform Overview',
      pendingApproval: 'Pending Approval',
      approved: 'Approved',
      suspended: 'Suspended',
      yourConversations: 'Your Conversations',
      yourOrders: 'Your Orders',
      orders: 'Orders',
      securitySettings: 'Security & Password',
      currentPassword: 'Current Password',
      newPassword: 'New Password',
      confirmPassword: 'Confirm New Password',
      updatePassword: 'Update Password',
      profileUpdated: 'Profile updated successfully!',
      passwordUpdated: 'Password updated successfully!',
      passwordMismatch: 'New passwords do not match!',
      remove: 'Remove',
      emptyWishlist: 'Your Saved Items list is empty.',
      wishlistTitle: 'Your Saved Items',
      wishlistSubtitle: 'Build your perfect wishlist of hand-crafted items.',
      goFindFavorites: 'Go Find Favorites',
      buyerProfile: 'Buyer Profile',
      sellerProfile: 'Seller Profile',
      adminProfile: 'Admin Profile',
      hello: 'Hello',
      welcomeDashboard: 'Welcome back to your control panel. Monitor purchases, view updates, and explore products.',
      totalPurchases: 'Total Purchases',
      savedFavorites: 'Saved Favorites',
      recentTransactions: 'Recent Transactions',
      trackOrder: 'Track Order',
      noTransactions: 'No transaction records found.',
      placedDate: 'Placed Date',
      priceTotal: 'Price Total',
      shipStatus: 'Ship Status',
      actions: 'Actions',
      notifications: 'Notifications',
      markAllRead: 'Mark all read',
      noNotifications: 'No notifications',
      workspace: 'workspace',
      shipments: 'Shipments',
      profile: 'Profile',
      filters: 'Filters',
      productDetails: 'Product Details',
      viewDetails: 'View Details',
      search: 'Search',
      category: 'Category',
      priceRange: 'Price Range',
      min: 'Min',
      max: 'Max',
      status: 'Status',
      allStatuses: 'All Statuses',
      dateRange: 'Date Range',
      sortOptions: 'Sort Options',
      clearFilters: 'Clear Filters',
      filterSortOptions: 'Filter & Sort Options',
      filterProducts: 'Filter Products',
      applyFilters: 'Apply Filters',
      back: 'Back',
      by: 'By',
      off: 'OFF',
      total: 'Total',
      items: 'Items',
      price: 'Price',
      subtotal: 'Subtotal',
      gst: 'Estimated GST (5%)',
      grandTotal: 'Grand Total Paid',
      placeOrder: 'Place Order',
      shippingAddress: 'Shipping Address',
      trackingNumber: 'Tracking Number',
      deliveryAddress: 'Delivery Address',
      myProducts: 'My Products',
      myCustomers: 'My Customers',
      salesAnalytics: 'Sales Analytics',
      salesRevenue: 'Sales Revenue',
      activeListings: 'Active Listings',
      ordersFulfilled: 'Orders Fulfilled',
      averageRating: 'Average Rating',
      stockStatus: 'Stock Status',
      inStock: 'In Stock',
      outOfStock: 'Out of Stock',
      lowStock: 'Low Stock',
    },
    hi: {
      browse: 'खोजें',
      inbox: 'इनबॉक्स',
      dashboard: 'डैशबोर्ड',
      addProduct: 'उत्पाद जोड़ें',
      addNewProduct: 'नया उत्पाद जोड़ें',
      logout: 'लॉगआउट',
      login: 'लॉग इन',
      register: 'रजिस्टर',
      searchPlaceholder: 'उत्पाद, श्रेणी, या विक्रेता खोजें...',
      addToCart: 'कार्ट में जोड़ें',
      addedToCart: 'कार्ट में जोड़ा गया ✓',
      buyNow: 'अभी खरीदें',
      chatWithSeller: 'विक्रेता से बात करें',
      loginToChat: 'बात करने के लिए लॉग इन करें',
      shoppingCart: 'शॉपिंग कार्ट',
      cart: 'कार्ट',
      orderSummary: 'ऑर्डर सारांश',
      proceedToCheckout: 'चेकआउट करें',
      paymentSuccess: 'भुगतान सफल रहा!',
      accountSettings: 'खाता सेटिंग्स',
      purchaseHistory: 'खरीद इतिहास',
      savedItems: 'पसंदीदा उत्पाद',
      entrepreneurDetails: 'उद्यमी का विवरण',
      marketPriceGuideline: 'बाजार मूल्य निर्देशिका',
      productDescription: 'उत्पाद विवरण',
      marketPrices: 'बाजार मूल्य',
      editProfile: 'प्रोफ़ाइल संपादित करें',
      saveChanges: 'परिवर्तन सहेजें',
      cancel: 'रद्द करें',
      starRating: 'स्टार रेटिंग',
      submitReview: 'समीक्षा जमा करें',
      vettingDashboard: 'उद्यमी समीक्षा',
      productModeration: 'उत्पाद समीक्षा',
      platformOverview: 'मंच अवलोकन',
      pendingApproval: 'अनुमोदन लंबित',
      approved: 'अनुमोदित',
      suspended: 'निलंबित',
      yourConversations: 'आपकी बातचीत',
      yourOrders: 'आपके ऑर्डर',
      orders: 'ऑर्डर',
      securitySettings: 'सुरक्षा और पासवर्ड',
      currentPassword: 'वर्तमान पासवर्ड',
      newPassword: 'नया पासवर्ड',
      confirmPassword: 'नए पासवर्ड की पुष्टि करें',
      updatePassword: 'पासवर्ड अपडेट करें',
      profileUpdated: 'प्रोफ़ाइल सफलतापूर्वक अपडेट हो गई!',
      passwordUpdated: 'पासवर्ड सफलतापूर्वक अपडेट हो गया!',
      passwordMismatch: 'नए पासवर्ड मेल नहीं खाते!',
      remove: 'हटाएं',
      emptyWishlist: 'आपकी पसंदीदा उत्पाद सूची खाली है।',
      wishlistTitle: 'आपके पसंदीदा उत्पाद',
      wishlistSubtitle: 'हस्तनिर्मित वस्तुओं की अपनी पसंदीदा सूची बनाएं।',
      goFindFavorites: 'पसंदीदा उत्पाद खोजें',
      buyerProfile: 'ग्राहक प्रोफ़ाइल',
      sellerProfile: 'विक्रेता प्रोफ़ाइल',
      adminProfile: 'प्रशासक प्रोफ़ाइल',
      hello: 'नमस्ते',
      welcomeDashboard: 'अपने नियंत्रण पैनल में आपका स्वागत है। खरीदारी और अपडेट देखें।',
      totalPurchases: 'कुल खरीदारी',
      savedFavorites: 'पसंदीदा उत्पाद',
      recentTransactions: 'हाल ही के लेन-देन',
      trackOrder: 'ऑर्डर ट्रैक करें',
      noTransactions: 'कोई लेन-देन रिकॉर्ड नहीं मिला।',
      placedDate: 'दिनांक',
      priceTotal: 'कुल कीमत',
      shipStatus: 'शिपमेंट स्थिति',
      actions: 'कार्रवाई',
      notifications: 'अधिसूचना',
      markAllRead: 'सभी को पढ़ा हुआ चिह्नित करें',
      noNotifications: 'कोई अधिसूचना नहीं',
      workspace: 'कार्यस्थान',
      shipments: 'शिपमेंट',
      profile: 'प्रोफ़ाइल',
      filters: 'फ़िल्टर',
      productDetails: 'उत्पाद विवरण',
      viewDetails: 'विवरण देखें',
      search: 'खोजें',
      category: 'श्रेणी',
      priceRange: 'मूल्य सीमा',
      min: 'न्यूनतम',
      max: 'अधिकतम',
      status: 'स्थिति',
      allStatuses: 'सभी स्थितियां',
      dateRange: 'तारीख सीमा',
      sortOptions: 'क्रमबद्ध करें',
      clearFilters: 'फ़िल्टर हटाएं',
      filterSortOptions: 'फ़िल्टर और क्रमबद्ध विकल्प',
      filterProducts: 'उत्पाद फ़िल्टर करें',
      applyFilters: 'फ़िल्टर लागू करें',
      back: 'वापस',
      by: 'द्वारा',
      off: 'छूट',
      total: 'कुल',
      items: 'वस्तुएं',
      price: 'कीमत',
      subtotal: 'उप-योग',
      gst: 'जीएसटी (5%)',
      grandTotal: 'कुल योग',
      placeOrder: 'ऑर्डर दें',
      shippingAddress: 'शिपिंग पता',
      trackingNumber: 'ट्रैकिंग नंबर',
      deliveryAddress: 'डिलीवरी का पता',
      myProducts: 'मेरे उत्पाद',
      myCustomers: 'मेरे ग्राहक',
      salesAnalytics: 'बिक्री विश्लेषण',
      salesRevenue: 'बिक्री आय',
      activeListings: 'सक्रिय उत्पाद',
      ordersFulfilled: 'पूरे किए गए ऑर्डर',
      averageRating: 'औसत रेटिंग',
      stockStatus: 'स्टॉक स्थिति',
      inStock: 'उपलब्ध',
      outOfStock: 'स्टॉक समाप्त',
      lowStock: 'कम स्टॉक',
    },
    te: {
      browse: 'బ్రౌజ్ చేయండి',
      inbox: 'ఇన్‌బాక్స్',
      dashboard: 'డాష్‌బోర్డ్',
      addProduct: 'ఉత్పత్తిని జోడించు',
      addNewProduct: 'కొత్త ఉత్పత్తిని జోడించండి',
      logout: 'లాగ్ అవుట్',
      login: 'లాగిన్',
      register: 'నమోదు చేయండి',
      searchPlaceholder: 'ఉత్పత్తులు, వర్గం లేదా అమ్మకందారులను శోధించండి...',
      addToCart: 'కార్ట్‌కు జోడించు',
      addedToCart: 'కార్ట్‌కు జోడించబడింది ✓',
      buyNow: 'ఇప్పుడే కొనండి',
      chatWithSeller: 'విక్రేతతో చాట్ చేయండి',
      loginToChat: 'చాట్ చేయడానికి లాగిన్ అవ్వండి',
      shoppingCart: 'షాపింగ్ కార్ట్',
      cart: 'కార్ట్',
      orderSummary: 'ఆర్డర్ సారాంశం',
      proceedToCheckout: 'చెక్అవుట్ చేయండి',
      paymentSuccess: 'చెల్లింపు విజయవంతమైంది!',
      accountSettings: 'ఖాతా సెట్టింగులు',
      purchaseHistory: 'కొనుగోలు చరిత్ర',
      savedItems: 'ప్రియమైన ఉత్పత్తులు',
      entrepreneurDetails: 'కార్యకర్త వివరాలు',
      marketPriceGuideline: 'మార్కెట్ ధర మార్గదర్శిని',
      productDescription: 'ఉత్పత్తి వివరణ',
      marketPrices: 'మార్కెట్ ధరలు',
      editProfile: 'ప్రొఫైల్ సవరించండి',
      saveChanges: 'మార్పులను సేవ్ చేయి',
      cancel: 'రద్దు చేయి',
      starRating: 'నక్షత్ర రేటింగ్',
      submitReview: 'సమీక్షను సమర్పించండి',
      vettingDashboard: 'నిర్వాహక ధృవీకరణ',
      productModeration: 'ఉత్పత్తి తనిఖీ',
      platformOverview: 'ప్లాట్‌ఫారమ్ అవలోకనం',
      pendingApproval: 'ఆమోదం పెండింగ్‌లో ఉంది',
      approved: 'ఆమోదించబడింది',
      suspended: 'తాత్కాలికంగా నిలిపివేయబడింది',
      yourConversations: 'మీ సంభాషణలు',
      yourOrders: 'మీ ఆర్డర్లు',
      orders: 'ఆర్డర్లు',
      securitySettings: 'భద్రత & పాస్‌వర్డ్',
      currentPassword: 'ప్రస్తుత పాస్‌వర్డ్',
      newPassword: 'కొత్త పాస్‌వర్డ్',
      confirmPassword: 'కొత్త పాస్‌వర్డ్‌ను నిర్ధారించండి',
      updatePassword: 'పాస్‌వర్డ్‌ను నవీకరించండి',
      profileUpdated: 'ప్రొఫైల్ విజయవంతంగా నవీకరించబడింది!',
      passwordUpdated: 'పాస్‌వర్డ్ విజయవంతంగా నవీకరించబడింది!',
      passwordMismatch: 'కొత్త పాస్‌వర్డ్‌లు సరిపోలడం లేదు!',
      remove: 'తొలగించు',
      emptyWishlist: 'మీ ప్రియమైన ఉత్పత్తుల జాబితా ఖాళీగా ఉంది.',
      wishlistTitle: 'మీ ప్రియమైన ఉత్పత్తులు',
      wishlistSubtitle: 'హస్తకళల పరిపూర్ణమైన కోరికల జాబితాను రూపొందించుకోండి.',
      goFindFavorites: 'ఇష్టమైన ఉత్పత్తులను కనుగొనండి',
      buyerProfile: 'కొనుగోలుదారు ప్రొఫైల్',
      sellerProfile: 'విక్రేత ప్రొఫైల్',
      adminProfile: 'అడ్మిన్ ప్రొఫైల్',
      hello: 'నమస్కారం',
      welcomeDashboard: 'మీ నియంత్రణ ప్యానెల్‌కు స్వాగతం.',
      totalPurchases: 'మొత్తం కొనుగోళ్లు',
      savedFavorites: 'ప్రియమైన ఉత్పత్తులు',
      recentTransactions: 'ఇటీవలి లావాదేవీలు',
      trackOrder: 'ఆర్డర్ ట్రాక్ చేయండి',
      noTransactions: 'ఎలాంటి లావాదేవీల రికార్డులు కనుగొనబడలేదు.',
      placedDate: 'తేదీ',
      priceTotal: 'మొత్తం ధర',
      shipStatus: 'షిప్‌మెంట్ స్థితి',
      actions: 'చర్యలు',
      notifications: 'నోటిఫికేషన్లు',
      markAllRead: 'అన్నింటినీ చదివినట్లు గుర్తు పెట్టండి',
      noNotifications: 'నోటిఫికేషన్‌లు లేవు',
      workspace: 'వర్క్‌స్పేస్',
      shipments: 'షిప్‌మెంట్‌లు',
      profile: 'ప్రొఫైల్',
      filters: 'ఫిల్టర్లు',
      productDetails: 'ఉత్పత్తి వివరాలు',
      viewDetails: 'వివరాలు చూడండి',
      search: 'శోధన',
      category: 'వర్గం',
      priceRange: 'ధర పరిధి',
      min: 'కనీసం',
      max: 'గరిష్టం',
      status: 'స్థితి',
      allStatuses: 'అన్ని స్థితులు',
      dateRange: 'తేదీ పరిధి',
      sortOptions: 'రకము',
      clearFilters: 'ఫిల్టర్లు తీసివేయి',
      filterSortOptions: 'ఫిల్టర్ మరియు సార్ట్ ఎంపికలు',
      filterProducts: 'ఉత్పత్తులను ఫిల్టర్ చేయండి',
      applyFilters: 'ఫిల్టర్లు నింపండి',
      back: 'వెనుకకు',
      by: 'ద్వారా',
      off: 'రాయితీ',
      total: 'మొత్తం',
      items: 'అంశాలు',
      price: 'ధర',
      subtotal: 'ఉప-మొత్తం',
      gst: 'జిఎస్‌టి (5%)',
      grandTotal: 'మొత్తం చెల్లించవలసినది',
      placeOrder: 'ఆర్డర్ చేయండి',
      shippingAddress: 'షిప్పింగ్ చిరునామా',
      trackingNumber: 'ట్రాకింగ్ సంఖ్య',
      deliveryAddress: 'డెలివరీ చిరునామా',
      myProducts: 'నా ఉత్పత్తులు',
      myCustomers: 'నా కస్టమర్లు',
      salesAnalytics: 'అమ్మకాల విశ్లేషణ',
      salesRevenue: 'అమ్మకాల ఆదాయం',
      activeListings: 'సక్రియ ఉత్పత్తులు',
      ordersFulfilled: 'పూర్తయిన ఆర్డర్లు',
      averageRating: 'సగటు రేటింగ్',
      stockStatus: 'స్టాక్ స్థితి',
      inStock: 'స్టాక్‌లో ఉంది',
      outOfStock: 'స్టాక్ అయిపోయింది',
      lowStock: 'తక్కువ స్టాక్',
    },
    ta: {
      browse: 'உலாவு',
      inbox: 'இன்பாக்ஸ்',
      dashboard: 'டாஷ்போர்டு',
      addProduct: 'தயாரிப்பைச் சேர்',
      addNewProduct: 'புதிய தயாரிப்பைச் சேர்',
      logout: 'வெளியேறு',
      login: 'உள்நுழைய',
      register: 'பதிவு செய்',
      searchPlaceholder: 'தயாரிப்புகள், வகை அல்லது விற்பனையாளர்களைத் தேடுக...',
      addToCart: 'வண்டியில் சேர்',
      addedToCart: 'வண்டியில் சேர்க்கப்பட்டது ✓',
      buyNow: 'இப்போதே வாங்கு',
      chatWithSeller: 'விற்பனையாளருடன் அரட்டையடி',
      loginToChat: 'அரட்டையடிக்க உள்நுழையவும்',
      shoppingCart: 'ஷாப்பிங் கார்ட்',
      cart: 'கார்ட்',
      orderSummary: 'ஆர்டர் சுருக்கம்',
      proceedToCheckout: 'செக்அவுட் செய்ய தொடரவும்',
      paymentSuccess: 'பணம் செலுத்துதல் வெற்றி!',
      accountSettings: 'கணக்கு அமைப்புகள்',
      purchaseHistory: 'கொள்முதல் வரலாறு',
      savedItems: 'சேமித்த பொருட்கள்',
      entrepreneurDetails: 'தொழில்முனைவோர் விவரங்கள்',
      marketPriceGuideline: 'சந்தை விலை வழிகாட்டி',
      productDescription: 'தயாரிப்பு விளக்கம்',
      marketPrices: 'சந்தை விலைகள்',
      editProfile: 'சுயவிவரத்தைத் திருத்து',
      saveChanges: 'மாற்றங்களைச் சேமிக்கவும்',
      cancel: 'ரத்துசெய்',
      starRating: 'நட்சத்திர மதிப்பீடு',
      submitReview: 'மதிப்பாய்வைச் சமர்ப்பி',
      vettingDashboard: 'தொழில்முனைவோர் சரிபார்ப்பு',
      productModeration: 'தயாரிப்பு மதிப்பாய்வு',
      platformOverview: 'தள கண்ணோட்டம்',
      pendingApproval: 'ஒப்புதல் நிலுவையில் உள்ளது',
      approved: 'அங்கீகரிக்கப்பட்டது',
      suspended: 'நிறுத்தி வைக்கப்பட்டது',
      yourConversations: 'உங்கள் உரையாடல்கள்',
      yourOrders: 'உங்கள் ஆர்டர்கள்',
      orders: 'ஆர்டர்கள்',
      securitySettings: 'பாதுகாப்பு & கடவுச்சொல்',
      currentPassword: 'தற்போதைய கடவுச்சொல்',
      newPassword: 'புதிய கடவுச்சொல்',
      confirmPassword: 'புதிய கடவுச்சொல்லை உறுதிப்படுத்தவும்',
      updatePassword: 'கடவுச்சொல்லைப் புதுப்பிக்கவும்',
      profileUpdated: 'சுயவிவரம் வெற்றிகரமாக புதுப்பிக்கப்பட்டது!',
      passwordUpdated: 'கடவுச்சொல் வெற்றிகரமாக புதுப்பிக்கப்பட்டது!',
      passwordMismatch: 'புதிய கடவுச்சொற்கள் பொருந்தவில்லை!',
      remove: 'அகற்று',
      emptyWishlist: 'உங்கள் சேமித்த பொருட்கள் பட்டியல் காலியாக உள்ளது.',
      wishlistTitle: 'உங்கள் சேமித்த பொருட்கள்',
      wishlistSubtitle: 'கைவினைப் பொருட்களின் உங்களது சரியான விருப்பப்பட்டியலை உருவாக்குங்கள்.',
      goFindFavorites: 'விருப்பமானவற்றைக் கண்டறியவும்',
      buyerProfile: 'வாங்குபவர் சுயவிவரம்',
      sellerProfile: 'விற்பனையாளர் சுயவிவரம்',
      adminProfile: 'நிர்வாகி சுயவிவரம்',
      hello: 'வணக்கம்',
      welcomeDashboard: 'உங்கள் கட்டுப்பாட்டு பலகத்திற்கு வரவேற்கிறோம்.',
      totalPurchases: 'மொத்த வாங்குதல்கள்',
      savedFavorites: 'சேமித்த பொருட்கள்',
      recentTransactions: 'சமீபத்திய பரிவர்த்தனைகள்',
      trackOrder: 'ஆர்டரைக் கண்காணிக்கவும்',
      noTransactions: 'பரிவர்த்தனை பதிவுகள் எதுவும் கிடைக்கவில்லை.',
      placedDate: 'தேதி',
      priceTotal: 'மொத்த விலை',
      shipStatus: 'ஷிப்மென்ட் நிலை',
      actions: 'செயல்கள்',
      notifications: 'அறிவிப்புகள்',
      markAllRead: 'அனைத்தையும் படித்ததாகக் குறிக்கவும்',
      noNotifications: 'அறிவிப்புகள் இல்லை',
      workspace: 'பணியிடம்',
      shipments: 'ஷிப்மென்ட்கள்',
      profile: 'சுயவிவரம்',
      filters: 'வடிப்பான்கள்',
      productDetails: 'தயாரிப்பு விவரங்கள்',
      viewDetails: 'விவரங்களைப் பார்க்கவும்',
      search: 'தேடல்',
      category: 'வகை',
      priceRange: 'விலை வரம்பு',
      min: 'குறைந்தபட்சம்',
      max: 'அதிகபட்சம்',
      status: 'நிலை',
      allStatuses: 'அனைத்து நிலைகளும்',
      dateRange: 'தேதி வரம்பு',
      sortOptions: 'வரிசைப்படுத்தல்',
      clearFilters: 'வடிப்பான்களை நீக்கு',
      filterSortOptions: 'வடிகட்டி & வரிசைப்படுத்து',
      filterProducts: 'தயாரிப்புகளை வடிகட்டவும்',
      applyFilters: 'வடிப்பான்களைப் பயன்படுத்துக',
      back: 'திரும்பிச் செல்',
      by: 'மூலம்',
      off: 'தள்ளுபடி',
      total: 'மொத்தம்',
      items: 'பொருட்கள்',
      price: 'விலை',
      subtotal: 'உள்-மொத்தம்',
      gst: 'ஜிஎஸ்டி (5%)',
      grandTotal: 'மொத்தக் கட்டணம்',
      placeOrder: 'ஆர்டர் செய்க',
      shippingAddress: 'ஷிப்பிங் முகவரி',
      trackingNumber: 'கண்காணிப்பு எண்',
      deliveryAddress: 'டெலிவரி முகவரி',
      myProducts: 'எனது தயாரிப்புகள்',
      myCustomers: 'எனது வாடிக்கையாளர்கள்',
      salesAnalytics: 'விற்பனை பகுப்பாய்வு',
      salesRevenue: 'விற்பனை வருவாய்',
      activeListings: 'செயலில் உள்ள தயாரிப்புகள்',
      ordersFulfilled: 'நிறைவேற்றப்பட்ட ஆர்டர்கள்',
      averageRating: 'சராசரி மதிப்பீடு',
      stockStatus: 'இருப்பு நிலை',
      inStock: 'இருப்பில் உள்ளது',
      outOfStock: 'இருப்பில் இல்லை',
      lowStock: 'குறைந்த இருப்பு',
    },
    kn: {
      browse: 'ಬ್ರೌಸ್ ಮಾಡಿ',
      inbox: 'ಇನ್‌ಬಾಕ್ಸ್',
      dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
      addProduct: 'ಉತ್ಪನ್ನ ಸೇರಿಸಿ',
      addNewProduct: 'ಹೊಸ ಉತ್ಪನ್ನ ಸೇರಿಸಿ',
      logout: 'ಲಾಗ್ ಔಟ್',
      login: 'ಲಾಗಿನ್',
      register: 'ನೋಂದಣಿ',
      searchPlaceholder: 'ಉತ್ಪನ್ನಗಳು, ವರ್ಗ ಅಥವಾ ಮಾರಾಟಗಾರರನ್ನು ಹುಡುಕಿ...',
      addToCart: 'ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಿ',
      addedToCart: 'ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಲಾಗಿದೆ ✓',
      buyNow: 'ಈಗಲೇ ಖರೀದಿಸಿ',
      chatWithSeller: 'ಮಾರಾಟಗಾರರೊಂದಿಗೆ ಚಾಟ್ ಮಾಡಿ',
      loginToChat: 'ಚಾಟ್ ಮಾಡಲು ಲಾಗಿನ್ ಮಾಡಿ',
      shoppingCart: 'ಶಾಪಿಂಗ್ ಕಾರ್ಟ್',
      cart: 'ಕಾರ್ಟ್',
      orderSummary: 'ಆರ್ಡರ್ ಸಾರಾಂಶ',
      proceedToCheckout: 'ಚೆಕ್‌ಔಟ್‌ಗೆ ಮುಂದುವರಿಯಿರಿ',
      paymentSuccess: 'ಪಾವತಿ ಯಶಸ್ವಿಯಾಗಿದೆ!',
      accountSettings: 'ಖಾತೆ ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
      purchaseHistory: 'ಖರೀದಿ ಇತಿಹಾಸ',
      savedItems: 'ಉಳಿಸಿದ ವಸ್ತುಗಳು',
      entrepreneurDetails: 'ಉದ್ಯಮಿಗಳ ವಿವರಗಳು',
      marketPriceGuideline: 'ಮಾರುಕಟ್ಟೆ ಬೆಲೆ ಮಾರ್ಗದರ್ಶಿ',
      productDescription: 'ಉತ್ಪನ್ನ ವಿವರಣೆ',
      marketPrices: 'ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಳು',
      editProfile: 'ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ',
      saveChanges: 'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ',
      cancel: 'ರದ್ದುಗೊಳಿಸಿ',
      starRating: 'ಸ್ಟಾರ್ ರೇಟಿಂಗ್',
      submitReview: 'ವಿಮರ್ಶೆ ಸಲ್ಲಿಸಿ',
      vettingDashboard: 'ಉದ್ಯಮಿ ಪರಿಶೀಲನೆ',
      productModeration: 'ಉತ್ಪನ್ನ ಪರಿಶೀಲನೆ',
      platformOverview: 'ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಅವಲೋಕನ',
      pendingApproval: 'ಅನುಮೋದನೆ ಬಾಕಿ ಇದೆ',
      approved: 'ಅನುಮೋದಿಸಲಾಗಿದೆ',
      suspended: 'ಅಮಾನತುಗೊಳಿಸಲಾಗಿದೆ',
      yourConversations: 'ನಿಮ್ಮ ಸಂಭಾಷಣೆಗಳು',
      yourOrders: 'ನಿಮ್ಮ ಆರ್ಡರ್‌ಗಳು',
      orders: 'ಆರ್ಡರ್‌ಗಳು',
      securitySettings: 'ಭದ್ರತೆ ಮತ್ತು ಪಾಸ್‌ವರ್ಡ್',
      currentPassword: 'ಪ್ರಸ್ತುತ ಪಾಸ್‌ವರ್ಡ್',
      newPassword: 'ಹೊಸ ಪಾಸ್‌ವರ್ಡ್',
      confirmPassword: 'ಹೊಸ ಪಾಸ್‌ವರ್ಡ್ ಖಚಿತಪಡಿಸಿ',
      updatePassword: 'ಪಾಸ್‌ವರ್ಡ್ ನವೀಕರಿಸಿ',
      profileUpdated: 'ಪ್ರೊಫೈಲ್ ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ!',
      passwordUpdated: 'ಪಾಸ್‌ವರ್ಡ್ ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ!',
      passwordMismatch: 'ಹೊಸ ಪಾಸ್‌ವರ್ಡ್‌ಗಳು ಹೊಂದಿಕೆಯಾಗುತ್ತಿಲ್ಲ!',
      remove: 'ತೆಗೆದುಹಾಕಿ',
      emptyWishlist: 'ನಿಮ್ಮ ಉಳಿಸಿದ ವಸ್ತುಗಳ ಪಟ್ಟಿ ಖಾಲಿ ಇದೆ.',
      wishlistTitle: 'ನಿಮ್ಮ ಉಳಿಸಿದ ವಸ್ತುಗಳು',
      wishlistSubtitle: 'ಹಸ್ತಕಲಾ ವಸ್ತುಗಳ ನಿಮ್ಮ ಪರಿಪೂರ್ಣ ಇಷ್ಟದ ಪಟ್ಟಿಯನ್ನು ನಿರ್ಮಿಸಿ.',
      goFindFavorites: 'ಮೆಚ್ಚಿನವುಗಳನ್ನು ಹುಡುಕಿ',
      buyerProfile: 'ಖರೀದಿದಾರರ ಪ್ರೊಫೈಲ್',
      sellerProfile: 'ಮಾರಾಟಗಾರರ ಪ್ರೊಫೈಲ್',
      adminProfile: 'ಅಡ್ಮಿನ್ ಪ್ರೊಫೈಲ್',
      hello: 'ನಮಸ್ಕಾರ',
      welcomeDashboard: 'ನಿಮ್ಮ ನಿಯಂತ್ರಣ ಫಲಕಕ್ಕೆ ಸುಸ್ವಾಗತ.',
      totalPurchases: 'ಒಟ್ಟು ಖರೀದಿಗಳು',
      savedFavorites: 'ಉಳಿಸಿದ ವಸ್ತುಗಳು',
      recentTransactions: 'ಇತ್ತೀಚಿನ ವಹಿವಾಟುಗಳು',
      trackOrder: 'ಆರ್ಡರ್ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
      noTransactions: 'ಯಾವುದೇ ವಹಿವಾಟು ದಾಖಲೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ.',
      placedDate: 'ದಿನಾಂಕ',
      priceTotal: 'ಒಟ್ಟು ಬೆಲೆ',
      shipStatus: 'ಶಿಪ್‌ಮೆಂಟ್ ಸ್ಥಿತಿ',
      actions: 'ಕ್ರಿಯೆಗಳು',
      notifications: 'ಸೂಚನೆಗಳು',
      markAllRead: 'ಎಲ್ಲವನ್ನೂ ಓದಲಾಗಿದೆ ಎಂದು ಗುರುತಿಸಿ',
      noNotifications: 'ಯಾವುದೇ ಸೂಚನೆಗಳಿಲ್ಲ',
      workspace: 'ಕಾರ್ಯಕ್ಷೇತ್ರ',
      shipments: 'ಶಿಪ್‌ಮೆಂಟ್‌ಗಳು',
      profile: 'ಪ್ರೊಫೈಲ್',
      filters: 'ಫಿಲ್ಟರ್‌ಗಳು',
      productDetails: 'ಉತ್ಪನ್ನ ವಿವರಗಳು',
      viewDetails: 'ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
      search: 'ಹುಡುಕಿ',
      category: 'ವರ್ಗ',
      priceRange: 'ಬೆಲೆ ಶ್ರೇಣಿ',
      min: 'ಕನಿಷ್ಠ',
      max: 'ಗರಿಷ್ಠ',
      status: 'ಸ್ಥಿತಿ',
      allStatuses: 'ಎಲ್ಲಾ ಸ್ಥಿತಿಗಳು',
      dateRange: 'ದಿನಾಂಕ ಶ್ರೇಣಿ',
      sortOptions: 'ವಿಂಗಡಣೆ',
      clearFilters: 'ಫಿಲ್ಟರ್‌ಗಳನ್ನು ತೆಗೆದುಹಾಕಿ',
      filterSortOptions: 'ಫಿಲ್ಟರ್ ಮತ್ತು ವಿಂಗಡಣೆ',
      filterProducts: 'ಉತ್ಪನ್ನಗಳನ್ನು ಫಿಲ್ಟರ್ ಮಾಡಿ',
      applyFilters: 'ಫಿಲ್ಟರ್‌ಗಳನ್ನು ಅನ್ವಯಿಸಿ',
      back: 'ಹಿಂದೆ',
      by: 'ಮೂಲಕ',
      off: 'ರಿಯಾಯಿತಿ',
      total: 'ಒಟ್ಟು',
      items: 'ವಸ್ತುಗಳು',
      price: 'ಬೆಲೆ',
      subtotal: 'ಉಪ-ಒಟ್ಟು',
      gst: 'ಜಿಎಸ್‌ಟಿ (5%)',
      grandTotal: 'ಒಟ್ಟು ಪಾವತಿಸಬೇಕಾದ ಮೊತ್ತ',
      placeOrder: 'ಆರ್ಡರ್ ಮಾಡಿ',
      shippingAddress: 'ಶಿಪ್ಪಿಂಗ್ ವಿಳಾಸ',
      trackingNumber: 'ಟ್ರ್ಯಾಕಿಂಗ್ ಸಂಖ್ಯೆ',
      deliveryAddress: 'ಡೆಲಿವರಿ ವಿಳಾಸ',
      myProducts: 'ನನ್ನ ಉತ್ಪನ್ನಗಳು',
      myCustomers: 'ನನ್ನ ಗ್ರಾಹಕರು',
      salesAnalytics: 'ಮಾರಾಟದ ವಿಶ್ಲೇಷಣೆ',
      salesRevenue: 'ಮಾರಾಟದ ಆದಾಯ',
      activeListings: 'ಸಕ್ರಿಯ ಉತ್ಪನ್ನಗಳು',
      ordersFulfilled: 'ಪೂರ್ಣಗೊಂಡ ಆರ್ಡರ್‌ಗಳು',
      averageRating: 'ಸರಾಸರಿ ರೇಟಿಂಗ್',
      stockStatus: 'ಸ್ಟಾಕ್ ಸ್ಥಿತಿ',
      inStock: 'ಸ್ಟಾಕ್‌ನಲ್ಲಿದೆ',
      outOfStock: 'ಸ್ಟಾಕ್ ಮುಗಿದಿದೆ',
      lowStock: 'ಕಡಿಮೆ ಸ್ಟಾಕ್',
    },
    ml: {
      browse: 'ബ്രൗസ് ചെയ്യുക',
      inbox: 'ഇൻബോക്സ്',
      dashboard: 'ഡാഷ്‌ബോർഡ്',
      addProduct: 'ഉൽപ്പന്നം ചേർക്കുക',
      addNewProduct: 'പുതിയ ഉൽപ്പന്നം ചേർക്കുക',
      logout: 'ലോഗ് ഔട്ട്',
      login: 'ലോഗിൻ',
      register: 'രജിസ്റ്റർ ചെയ്യുക',
      searchPlaceholder: 'ഉൽപ്പന്നങ്ങൾ, വിഭാഗം അല്ലെങ്കിൽ വിൽപ്പനക്കാരെ തിരയുക...',
      addToCart: 'കാർട്ടിലേക്ക് ചേർക്കുക',
      addedToCart: 'കാർട്ടിൽ ചേർത്തു ✓',
      buyNow: 'ഇപ്പോൾ വാങ്ങുക',
      chatWithSeller: 'വിൽപ്പനക്കാരനുമായി ചാറ്റ് ചെയ്യുക',
      loginToChat: 'ചാറ്റ് ചെയ്യാൻ ലോഗിൻ ചെയ്യുക',
      shoppingCart: 'ഷോപ്പിംഗ് കാർട്ട്',
      cart: 'കാർട്ട്',
      orderSummary: 'ഓർഡർ സംഗ്രഹം',
      proceedToCheckout: 'ചെക്ക്ഔട്ടിലേക്ക് പോകുക',
      paymentSuccess: 'പേയ്‌മെന്റ് വിജയകരമായി!',
      accountSettings: 'അക്കൗണ്ട് ക്രമീകരണങ്ങൾ',
      purchaseHistory: 'വാങ്ങൽ ചരിത്രം',
      savedItems: 'സംരക്ഷിച്ചവ',
      entrepreneurDetails: 'സംരംഭകരുടെ വിവരങ്ങൾ',
      marketPriceGuideline: 'മാർക്കറ്റ് വില വിവരങ്ങൾ',
      productDescription: 'ഉൽപ്പന്ന വിവരണം',
      marketPrices: 'മാർക്കറ്റ് വിലകൾ',
      editProfile: 'പ്രൊഫൈൽ എഡിറ്റ് ചെയ്യുക',
      saveChanges: 'മാറ്റങ്ങൾ സംരക്ഷിക്കുക',
      cancel: 'റദ്ദാക്കുക',
      starRating: 'സ്റ്റാർ റേറ്റിംഗ്',
      submitReview: 'അഭിപ്രായം രേഖപ്പെടുത്തുക',
      vettingDashboard: 'സംരംഭക പരിശോധന',
      productModeration: 'ഉൽപ്പന്ന പരിശോധന',
      platformOverview: 'പ്ലാറ്റ്ഫോം അവലോകനം',
      pendingApproval: 'അംഗീകാരം ലഭിക്കാനുണ്ട്',
      approved: 'അംഗീകരിച്ചു',
      suspended: 'സസ്പെൻഡ് ചെയ്തു',
      yourConversations: 'നിങ്ങളുടെ സംഭാഷണങ്ങൾ',
      yourOrders: 'നിങ്ങളുടെ ഓർഡറുകൾ',
      orders: 'ഓർഡറുകൾ',
      securitySettings: 'സുരക്ഷയും പാസ്‌വേഡും',
      currentPassword: 'നിലവിലെ പാസ്‌വേഡ്',
      newPassword: 'പുതിയ പാസ്‌വേഡ്',
      confirmPassword: 'പുതിയ പാസ്‌വേഡ് സ്ഥിരീകരിക്കുക',
      updatePassword: 'പാസ്‌വേഡ് അപ്‌ഡേറ്റ് ചെയ്യുക',
      profileUpdated: 'പ്രൊഫൈൽ വിജയകരമായി അപ്‌ഡേറ്റ് ചെയ്തു!',
      passwordUpdated: 'പാസ്‌വേഡ് വിജയകരമായി അപ്‌ഡേറ്റ് ചെയ്തു!',
      passwordMismatch: 'പുതിയ പാസ്‌വേഡുകൾ പൊരുത്തപ്പെടുന്നില്ല!',
      remove: 'ഒഴിവാക്കുക',
      emptyWishlist: 'നിങ്ങൾ സംരക്ഷിച്ച ഇനങ്ങൾ ഒന്നുമില്ല.',
      wishlistTitle: 'നിങ്ങൾ സംരക്ഷിച്ചവ',
      wishlistSubtitle: 'നിങ്ങളുടെ മികച്ച ഇഷ്ടാനിഷ്ടങ്ങളുടെ ലിസ്റ്റ് തയ്യാറാക്കുക.',
      goFindFavorites: 'ഇഷ്ടപ്പെട്ടവ കണ്ടെത്തുക',
      buyerProfile: 'വാങ്ങുന്നയാളുടെ പ്രൊഫൈൽ',
      sellerProfile: 'വിൽപ്പനക്കാരന്റെ പ്രൊഫൈൽ',
      adminProfile: 'അഡ്മിൻ പ്രൊഫൈൽ',
      hello: 'നമസ്കാരം',
      welcomeDashboard: 'നിങ്ങളുടെ കണ്ട്രോൾ പാനലിലേക്ക് സ്വാഗതം.',
      totalPurchases: 'ആകെ വാങ്ങലുകൾ',
      savedFavorites: 'സംരക്ഷിച്ചവ',
      recentTransactions: 'സമീപകാല ഇടപാടുകൾ',
      trackOrder: 'ഓർഡർ ട്രാക്ക് ചെയ്യുക',
      noTransactions: 'ഇടപാട് വിവരങ്ങൾ ഒന്നും ലഭ്യമല്ല.',
      placedDate: 'തീയതി',
      priceTotal: 'ആകെ തുക',
      shipStatus: 'ഷിപ്പ്മെന്റ് അവസ്ഥ',
      actions: 'നടപടികൾ',
      notifications: 'അറിയിപ്പുകൾ',
      markAllRead: 'എല്ലാം വായിച്ചതായി അടയാളപ്പെടുത്തുക',
      noNotifications: 'അറിയിപ്പുകൾ ഒന്നുമില്ല',
      workspace: 'വർക്ക്സ്പേസ്',
      shipments: 'ഷിപ്പ്മെന്റുകൾ',
      profile: 'പ്രൊഫൈൽ',
      filters: 'ഫിൽട്ടറുകൾ',
      productDetails: 'ഉൽപ്പന്ന വിവരങ്ങൾ',
      viewDetails: 'വിശദാംശങ്ങൾ കാണുക',
      search: 'തിരയുക',
      category: 'വിഭാഗം',
      priceRange: 'വില പരിധി',
      min: 'കുറഞ്ഞത്',
      max: 'കൂടിയത്',
      status: 'അവസ്ഥ',
      allStatuses: 'എല്ലാ അവസ്ഥകളും',
      dateRange: 'തീയതി പരിധി',
      sortOptions: 'ക്രമീകരിക്കുക',
      clearFilters: 'ഫിൽട്ടറുകൾ മാറ്റുക',
      filterSortOptions: 'ഫിൽട്ടർ & ക്രമീകരിക്കൽ',
      filterProducts: 'ഉൽപ്പന്നങ്ങൾ ഫിൽട്ടർ ചെയ്യുക',
      applyFilters: 'ഫിൽട്ടറുകൾ പ്രയോഗിക്കുക',
      back: 'തിരികെ',
      by: 'തയ്യാറാക്കിയത്',
      off: 'ഇളവ്',
      total: 'ആകെ',
      items: 'ഇനങ്ങൾ',
      price: 'വില',
      subtotal: 'ഉപ-ആകെ',
      gst: 'ജിഎസ്ടി (5%)',
      grandTotal: 'ആകെ നൽകേണ്ട തുക',
      placeOrder: 'ഓർഡർ നൽകുക',
      shippingAddress: 'ഷിപ്പിംഗ് വിലാസം',
      trackingNumber: 'ട്രാക്കിംഗ് നമ്പർ',
      deliveryAddress: 'ഡെലിവറി വിലാസം',
      myProducts: 'എന്റെ ഉൽപ്പന്നങ്ങൾ',
      myCustomers: 'എന്റെ ഉപഭോക്താക്കൾ',
      salesAnalytics: 'വിൽപ്പന അവലോകനം',
      salesRevenue: 'വിൽപ്പന വരുമാനം',
      activeListings: 'ലഭ്യമായ ഉൽപ്പന്നങ്ങൾ',
      ordersFulfilled: 'പൂർത്തിയാക്കിയ ഓർഡറുകൾ',
      averageRating: 'ശരാശരി റേറ്റിംഗ്',
      stockStatus: 'സ്റ്റോക്ക് അവസ്ഥ',
      inStock: 'സ്റ്റോക്കിലുണ്ട്',
      outOfStock: 'സ്റ്റോക്കില്ല',
      lowStock: 'കുറഞ്ഞ സ്റ്റോക്ക്',
    },
    mr: {
      browse: 'शोध घ्या',
      inbox: 'इन्बॉक्स',
      dashboard: 'डॅशबोर्ड',
      addProduct: 'उत्पादन जोडा',
      addNewProduct: 'नवीन उत्पादन जोडा',
      logout: 'लॉगआउट',
      login: 'लॉगिन',
      register: 'नोंदणी करा',
      searchPlaceholder: 'उत्पादने, श्रेणी किंवा विक्रेते शोधा...',
      addToCart: 'कार्टमध्ये जोडा',
      addedToCart: 'कार्टमध्ये जोडले गेले ✓',
      buyNow: 'आत्ताच खरेदी करा',
      chatWithSeller: 'विक्रेत्याशी चॅट करा',
      loginToChat: 'चॅट करण्यासाठी लॉगिन करा',
      shoppingCart: 'शॉपिंग कार्ट',
      cart: 'कार्ट',
      orderSummary: 'ऑर्डरचा सारांश',
      proceedToCheckout: 'चेकआऊट करा',
      paymentSuccess: 'पेमेंट यशस्वी झाले!',
      accountSettings: 'खाते सेटिंग्ज',
      purchaseHistory: 'खरेदीचा इतिहास',
      savedItems: 'जतन केलेल्या वस्तू',
      entrepreneurDetails: 'उद्योजिकेचा तपशील',
      marketPriceGuideline: 'बाजार भाव मार्गदर्शिका',
      productDescription: 'उत्पादन वर्णन',
      marketPrices: 'बाजार भाव',
      editProfile: 'प्रोफाईल संपादित करा',
      saveChanges: 'बदल जतन करा',
      cancel: 'रद्द करा',
      starRating: 'स्टार रेटिंग',
      submitReview: 'पुनरावलोकन सबमिट करा',
      vettingDashboard: 'उद्योजिका पडताळणी',
      productModeration: 'उत्पादन पडताळणी',
      platformOverview: 'प्लॅटफॉर्म विहंगावलोकन',
      pendingApproval: 'मंजुरी प्रलंबित',
      approved: 'मंजूर',
      suspended: 'निलंबित',
      yourConversations: 'तुमचे संभाषण',
      yourOrders: 'तुमच्या ऑर्डर्स',
      orders: 'ऑर्डर्स',
      securitySettings: 'सुरक्षा आणि पासवर्ड',
      currentPassword: 'सध्याचा पासवर्ड',
      newPassword: 'नवीन पासवर्ड',
      confirmPassword: 'नवीन पासवर्डची पुष्टी करा',
      updatePassword: 'पासवर्ड अपडेट करा',
      profileUpdated: 'प्रोफाईल यशस्वीरित्या अपडेट झाली!',
      passwordUpdated: 'पासवर्ड यशस्वीरित्या अपडेट झाला!',
      passwordMismatch: 'नवीन पासवर्ड जुळत नाहीत!',
      remove: 'काढून टाका',
      emptyWishlist: 'तुमची जतन केलेल्या वस्तूंची यादी रिकामी आहे.',
      wishlistTitle: 'तुमच्या जतन केलेल्या वस्तू',
      wishlistSubtitle: 'हस्तनिर्मित वस्तूंची तुमची आवडती यादी तयार करा.',
      goFindFavorites: 'आवडत्या वस्तू शोधा',
      buyerProfile: 'ग्राहक प्रोफाईल',
      sellerProfile: 'विक्रेता प्रोफाईल',
      adminProfile: 'प्रशासक प्रोफाईल',
      hello: 'नमस्कार',
      welcomeDashboard: 'तुमच्या नियंत्रण पॅनेलमध्ये आपले स्वागत आहे.',
      totalPurchases: 'एकूण खरेदी',
      savedFavorites: 'जतन केलेल्या वस्तू',
      recentTransactions: 'अलीकडील व्यवहार',
      trackOrder: 'ऑर्डर ट्रॅक करा',
      noTransactions: 'कोणताही व्यवहार आढळला नाही.',
      placedDate: 'दिनांक',
      priceTotal: 'एकूण किंमत',
      shipStatus: 'शिपमेंट स्थिती',
      actions: 'कृती',
      notifications: 'सूचना',
      markAllRead: 'सर्व वाचलेले म्हणून चिन्हांकित करा',
      noNotifications: 'कोणतीही सूचना नाही',
      workspace: 'कार्यस्थान',
      shipments: 'शिपमेंट्स',
      profile: 'प्रोफाईल',
      filters: 'फिल्टर्स',
      productDetails: 'उत्पादन तपशील',
      viewDetails: 'तपशील पहा',
      search: 'शोधा',
      category: 'श्रेणी',
      priceRange: 'किंमत श्रेणी',
      min: 'कमीत कमी',
      max: 'जास्तीत जास्त',
      status: 'स्थिती',
      allStatuses: 'सर्व स्थिती',
      dateRange: 'दिनांक श्रेणी',
      sortOptions: 'क्रमवारी',
      clearFilters: 'फिल्टर्स काढा',
      filterSortOptions: 'फिल्टर आणि क्रमवारी',
      filterProducts: 'उत्पादने फिल्टर करा',
      applyFilters: 'फिल्टर्स लागू करा',
      back: 'मागे',
      by: 'द्वारे',
      off: 'सवलत',
      total: 'एकूण',
      items: 'वस्तू',
      price: 'किंमत',
      subtotal: 'उप-एकूण',
      gst: 'जीएसटी (5%)',
      grandTotal: 'एकूण देय रक्कम',
      placeOrder: 'ऑर्डर द्या',
      shippingAddress: 'शिपिंग पत्ता',
      trackingNumber: 'ट्रॅकिंग नंबर',
      deliveryAddress: 'डिलीव्हरी पत्ता',
      myProducts: 'माझी उत्पादने',
      myCustomers: 'माझे ग्राहक',
      salesAnalytics: 'विक्री विश्लेषण',
      salesRevenue: 'विक्री उत्पन्न',
      activeListings: 'सक्रिय उत्पादने',
      ordersFulfilled: 'पूर्ण झालेल्या ऑर्डर्स',
      averageRating: 'सरासरी रेटिंग',
      stockStatus: 'स्टॉक स्थिती',
      inStock: 'स्टॉकमध्ये उपलब्ध',
      outOfStock: 'स्टॉक संपला',
      lowStock: 'कमी स्टॉक',
    },
    bn: {
      browse: 'খুঁজুন',
      inbox: 'ইনবক্স',
      dashboard: 'ড্যাশবোর্ড',
      addProduct: 'পণ্য যোগ করুন',
      addNewProduct: 'নতুন পণ্য যোগ করুন',
      logout: 'লগআউট',
      login: 'লগইন',
      register: 'রেজিস্টার',
      searchPlaceholder: 'পণ্য, বিভাগ বা বিক্রেতা খুঁজুন...',
      addToCart: 'কার্টে যোগ করুন',
      addedToCart: 'কার্টে যোগ করা হয়েছে ✓',
      buyNow: 'এখনই কিনুন',
      chatWithSeller: 'বিক্রেতার সাথে চ্যাট করুন',
      loginToChat: 'চ্যাট করতে লগইন করুন',
      shoppingCart: 'শপিং কার্ট',
      cart: 'কার্ট',
      orderSummary: 'অর্ডারের বিবরণ',
      proceedToCheckout: 'চেকআউটে যান',
      paymentSuccess: 'পেমেন্ট সফল হয়েছে!',
      accountSettings: 'অ্যাকাউন্ট সেটিংস',
      purchaseHistory: 'ক্রয় ইতিহাস',
      savedItems: 'পছন্দের তালিকা',
      entrepreneurDetails: 'উদ্যোক্তার বিবরণ',
      marketPriceGuideline: 'বাজার মূল্য নির্দেশিকা',
      productDescription: 'পণ্যের বিবরণ',
      marketPrices: 'বাজার মূল্য',
      editProfile: 'প্রোফাইল সম্পাদনা',
      saveChanges: 'পরিবর্তন সংরক্ষণ',
      cancel: 'বাতিল',
      starRating: 'স্টার রেটিং',
      submitReview: 'রিভিউ দিন',
      vettingDashboard: 'উদ্যোক্তা যাচাইকরণ',
      productModeration: 'পণ্য যাচাইকরণ',
      platformOverview: 'প্ল্যাটফর্মের বিবরণ',
      pendingApproval: 'অনুমোদন পেন্ডিং',
      approved: 'অনুমোদিত',
      suspended: 'স্থগিত',
      yourConversations: 'আপনার চ্যাটসমূহ',
      yourOrders: 'আপনার অর্ডারসমূহ',
      orders: 'অর্ডারসমূহ',
      securitySettings: 'সুরক্ষা এবং পাসওয়ার্ড',
      currentPassword: 'বর্তমান পাসওয়ার্ড',
      newPassword: 'নতুন পাসওয়ার্ড',
      confirmPassword: 'নতুন পাসওয়ার্ড নিশ্চিত করুন',
      updatePassword: 'পাসওয়ার্ড আপডেট করুন',
      profileUpdated: 'প্রোফাইল সফলভাবে আপডেট করা হয়েছে!',
      passwordUpdated: 'পাসওয়ার্ড সফলভাবে আপডেট করা হয়েছে!',
      passwordMismatch: 'নতুন পাসওয়ার্ড মেলেনি!',
      remove: 'মুছুন',
      emptyWishlist: 'আপনার পছন্দের তালিকা খালি।',
      wishlistTitle: 'আপনার পছন্দের পণ্যসমূহ',
      wishlistSubtitle: 'হস্তশিল্প পণ্যের নিজস্ব পছন্দের তালিকা তৈরি করুন।',
      goFindFavorites: 'পছন্দের পণ্য খুঁজুন',
      buyerProfile: 'ক্রেতার প্রোফাইল',
      sellerProfile: 'বিক্রেতার প্রোফাইল',
      adminProfile: 'অ্যাডমিন প্রোফাইল',
      hello: 'হ্যালো',
      welcomeDashboard: 'আপনার কন্ট্রোল প্যানেলে স্বাগতম।',
      totalPurchases: 'মোট ক্রয়',
      savedFavorites: 'পছন্দের তালিকা',
      recentTransactions: 'সাম্প্রতিক লেনদেন',
      trackOrder: 'অর্ডার ট্র্যাকিং',
      noTransactions: 'কোনো লেনদেন রেকর্ড পাওয়া যায়নি।',
      placedDate: 'তারিখ',
      priceTotal: 'মোট মূল্য',
      shipStatus: 'শিপমেন্ট অবস্থা',
      actions: 'পদক্ষেপ',
      notifications: 'বিজ্ঞপ্তি',
      markAllRead: 'সবগুলি পঠিত হিসাবে চিহ্নিত করুন',
      noNotifications: 'কোনো বিজ্ঞপ্তি নেই',
      workspace: 'ওয়ার্কস্পেস',
      shipments: 'শিপমেন্টসমূহ',
      profile: 'প্রোফাইল',
      filters: 'ফিল্টার',
      productDetails: 'পণ্যের বিবরণ',
      viewDetails: 'বিস্তারিত দেখুন',
      search: 'অনুসন্ধান',
      category: 'বিভাগ',
      priceRange: 'মূল্য সীমা',
      min: 'সর্বনিম্ন',
      max: 'সর্বোচ্চ',
      status: 'অবস্থা',
      allStatuses: 'সকল অবস্থা',
      dateRange: 'তারিখের সীমা',
      sortOptions: 'সাজানো',
      clearFilters: 'ফিল্টার মুছুন',
      filterSortOptions: 'ফিল্টার ও সাজানো',
      filterProducts: 'পণ্য ফিল্টার করুন',
      applyFilters: 'ফিল্টার প্রয়োগ করুন',
      back: 'ফিরে যান',
      by: 'দ্বারা',
      off: 'ছাড়',
      total: 'মোট',
      items: 'পণ্যসমূহ',
      price: 'দাম',
      subtotal: 'উপ-মোট',
      gst: 'জিএসটি (৫%)',
      grandTotal: 'সর্বমোট প্রদেয়',
      placeOrder: 'অর্ডার দিন',
      shippingAddress: 'শিপিং ঠিকানা',
      trackingNumber: 'ট্র্যাকিং নম্বর',
      deliveryAddress: 'ডেলিভারি ঠিকানা',
      myProducts: 'আমার পণ্যসমূহ',
      myCustomers: 'আমার গ্রাহকগণ',
      salesAnalytics: 'বিক্রয় বিশ্লেষণ',
      salesRevenue: 'বিক্রয় আয়',
      activeListings: 'সক্রিয় পণ্যসমূহ',
      ordersFulfilled: 'সম্পন্ন অর্ডারসমূহ',
      averageRating: 'গড় রেটিং',
      stockStatus: 'স্টক অবস্থা',
      inStock: 'স্টকে আছে',
      outOfStock: 'স্টক শেষ',
      lowStock: 'কম স্টক',
    },
    gu: {
      browse: 'શોધો',
      inbox: 'ઇનબોક્સ',
      dashboard: 'ડેશબોર્ડ',
      addProduct: 'ઉત્પાદન ઉમેરો',
      addNewProduct: 'નવું ઉત્પાદન ઉમેરો',
      logout: 'લોગઆઉટ',
      login: 'લોગિન',
      register: 'રજીસ્ટર કરો',
      searchPlaceholder: 'ઉત્પાદન, શ્રેણી અથવા વિક્રેતા શોધો...',
      addToCart: 'કાર્ટમાં ઉમેરો',
      addedToCart: 'કાર્ટમાં ઉમેરાયું ✓',
      buyNow: 'હમણાં ખરીદો',
      chatWithSeller: 'વિક્રેતા સાથે ચેટ કરો',
      loginToChat: 'ચેટ કરવા લોગિન કરો',
      shoppingCart: 'શોપિંગ કાર્ટ',
      cart: 'કાર્ટ',
      orderSummary: 'ઓર્ડર સારાંશ',
      proceedToCheckout: 'ચેકઆઉટ કરો',
      paymentSuccess: 'ચુકવણી સફળ રહી!',
      accountSettings: 'ખાતા સેટિંગ્સ',
      purchaseHistory: 'ખરીદીનો ઇતિહાસ',
      savedItems: 'પસંદગીની વસ્તુઓ',
      entrepreneurDetails: 'ઉદ્યોગસાહસિક વિગતો',
      marketPriceGuideline: 'બજાર ભાવ માર્ગદર્શિકા',
      productDescription: 'ઉત્પાદન વર્ણન',
      marketPrices: 'બજાર ભાવો',
      editProfile: 'પ્રોફાઇલ સંપાદિત કરો',
      saveChanges: 'ફેરફારો સાચવો',
      cancel: 'રદ કરો',
      starRating: 'સ્ટાર રેટિંગ',
      submitReview: 'સમીક્ષા સબમિટ કરો',
      vettingDashboard: 'ઉદ્યોગસાહસિક ચકાસણી',
      productModeration: 'ઉત્પાદન ચકાસણી',
      platformOverview: 'પ્લેટફોર્મ વિહંગાવલોકન',
      pendingApproval: 'મંજૂરી બાકી છે',
      approved: 'મંજૂર',
      suspended: 'સ્થગિત',
      yourConversations: 'તમારી વાતચીત',
      yourOrders: 'તમારા ઓર્ડર્સ',
      orders: 'ઓર્ડર્સ',
      securitySettings: 'સુરક્ષા અને પાસવર્ડ',
      currentPassword: 'વર્તમાન પાસવર્ડ',
      newPassword: 'નવો પાસવર્ડ',
      confirmPassword: 'નવા પાસવર્ડની પુષ્ટિ કરો',
      updatePassword: 'પાસવર્ડ અપડેટ કરો',
      profileUpdated: 'પ્રોફાઇલ સફળતાપૂર્વક અપડેટ થઈ!',
      passwordUpdated: 'પાસવર્ડ સફળતાપૂર્વક અપડેટ થયો!',
      passwordMismatch: 'નવા પાસવર્ડ મેળ ખાતા નથી!',
      remove: 'દૂર કરો',
      emptyWishlist: 'તમારી પસંદગીની વસ્તુઓની યાદી ખાલી છે.',
      wishlistTitle: 'તમારી પસંદગીની વસ્તુઓ',
      wishlistSubtitle: 'હસ્તકલા વસ્તુઓની તમારી આદર્શ વિશલિસ્ટ બનાવો.',
      goFindFavorites: 'પસંદગીની વસ્તુઓ શોધો',
      buyerProfile: 'ગ્રાહક પ્રોફાઇલ',
      sellerProfile: 'વિક્રેતા પ્રોફાઇલ',
      adminProfile: 'એડમિન પ્રોફાઇલ',
      hello: 'નમસ્તે',
      welcomeDashboard: 'તમારા કંટ્રોલ પેનલમાં આપનું સ્વાગત છે.',
      totalPurchases: 'કુલ ખરીદી',
      savedFavorites: 'પસંદગીની વસ્તુઓ',
      recentTransactions: 'તાજેતરના વ્યવહારો',
      trackOrder: 'ઓર્ડર ટ્રેક કરો',
      noTransactions: 'કોઈ વ્યવહાર રેકોર્ડ મળ્યો નથી.',
      placedDate: 'તારીખ',
      priceTotal: 'કુલ કિંમત',
      shipStatus: 'શિપમેન્ટ સ્થિતિ',
      actions: 'પગલાં',
      notifications: 'સૂચનાઓ',
      markAllRead: 'બધા વાંચેલા તરીકે ચિહ્નિત કરો',
      noNotifications: 'કોઈ સૂચનાઓ નથી',
      workspace: 'વર્કસ્પેસ',
      shipments: 'શિપમેન્ટ્સ',
      profile: 'પ્રોફાઇલ',
      filters: 'ફિલ્ટર્સ',
      productDetails: 'ઉત્પાદન વિગતો',
      viewDetails: 'વિગતો જુઓ',
      search: 'શોધો',
      category: 'શ્રેણી',
      priceRange: 'કિંમત શ્રેણી',
      min: 'ન્યૂનતમ',
      max: 'મહત્તમ',
      status: 'સ્થિતિ',
      allStatuses: 'તમામ સ્થિતિ',
      dateRange: 'તારીખ શ્રેણી',
      sortOptions: 'ક્રમબદ્ધ કરો',
      clearFilters: 'ફિલ્ટર્સ દૂર કરો',
      filterSortOptions: 'ફિલ્ટર અને ક્રમબદ્ધ કરો',
      filterProducts: 'ઉત્પાદનો ફિલ્ટર કરો',
      applyFilters: 'ફિલ્ટર્સ લાગુ કરો',
      back: 'પાછા જાઓ',
      by: 'દ્વારા',
      off: 'ડિસ્કાઉન્ટ',
      total: 'કુલ',
      items: 'વસ્તુઓ',
      price: 'કિંમત',
      subtotal: 'સબટ્રિપલ',
      gst: 'જીએસટી (5%)',
      grandTotal: 'કુલ ચૂકવવાપાત્ર',
      placeOrder: 'ઓર્ડર આપો',
      shippingAddress: 'શિપિંગ સરનામું',
      trackingNumber: 'ટ્રેકિંગ નંબર',
      deliveryAddress: 'ડિલિવરી સરનામું',
      myProducts: 'મારા ઉત્પાદનો',
      myCustomers: 'મારા ગ્રાહકો',
      salesAnalytics: 'વેચાણ વિશ્લેષણ',
      salesRevenue: 'વેચાણ આવક',
      activeListings: 'સક્રિય ઉત્પાદનો',
      ordersFulfilled: 'પૂર્ણ થયેલા ઓર્ડર્સ',
      averageRating: 'સરેરાશ રેટિંગ',
      stockStatus: 'સ્ટોક સ્થિતિ',
      inStock: 'સ્ટોકમાં ઉપલબ્ધ',
      outOfStock: 'સ્ટોક પૂરો',
      lowStock: 'ઓછો સ્ટોક',
    },
    pa: {
      browse: 'ਖੋਜੋ',
      inbox: 'ਇਨਬਾਕਸ',
      dashboard: 'ਡੈਸ਼ਬੋਰਡ',
      addProduct: 'ਉਤਪਾਦ ਜੋੜੋ',
      addNewProduct: 'ਨਵਾਂ ਉਤਪਾਦ ਜੋੜੋ',
      logout: 'ਲੌਗਆਊਟ',
      login: 'ਲੌਗਇਨ',
      register: 'ਰਜਿਸਟਰ ਕਰੋ',
      searchPlaceholder: 'ਉਤਪਾਦ, ਸ਼੍ਰੇਣੀ ਜਾਂ ਵਿਕਰੇਤਾ ਖੋਜੋ...',
      addToCart: 'ਕਾਰਟ ਵਿੱਚ ਜੋੜੋ',
      addedToCart: 'ਕਾਰਟ ਵਿੱਚ ਜੋੜਿਆ ਗਿਆ ✓',
      buyNow: 'ਹੁਣੇ ਖਰੀਦੋ',
      chatWithSeller: 'ਵਿਕਰੇਤਾ ਨਾਲ ਗੱਲਬਾਤ ਕਰੋ',
      loginToChat: 'ਗੱਲਬਾਤ ਲਈ ਲੌਗਇਨ ਕਰੋ',
      shoppingCart: 'ਸ਼ਾਪਿੰਗ ਕਾਰਟ',
      cart: 'ਕਾਰਟ',
      orderSummary: 'ਆਰਡਰ ਸਾਰਾਂਸ਼',
      proceedToCheckout: 'ਚੈੱਕਆਊਟ ਕਰੋ',
      paymentSuccess: 'ਭੁਗਤਾਨ ਸਫਲ ਰਿਹਾ!',
      accountSettings: 'ਖਾਤਾ ਸੈਟਿੰਗਜ਼',
      purchaseHistory: 'ਖਰੀਦ ਇਤਿਹਾਸ',
      savedItems: 'ਪਸੰਦੀਦਾ ਉਤਪਾਦ',
      entrepreneurDetails: 'ਉੱਦਮੀ ਦੇ ਵੇਰਵੇ',
      marketPriceGuideline: 'ਬਾਜ਼ਾਰ ਕੀਮਤ ਨਿਰਦੇਸ਼ਿਕਾ',
      productDescription: 'ਉਤਪਾਦ ਵੇਰਵਾ',
      marketPrices: 'ਬਾਜ਼ਾਰ ਕੀਮਤਾਂ',
      editProfile: 'ਪ੍ਰੋਫਾਈਲ ਸੋਧੋ',
      saveChanges: 'ਤਬਦੀਲੀਆਂ ਸੁਰੱਖਿਅਤ ਕਰੋ',
      cancel: 'ਰੱਦ ਕਰੋ',
      starRating: 'ਸਟਾਰ ਰੇਟਿੰਗ',
      submitReview: 'ਸਮੀਖਿਆ ਦਰਜ ਕਰੋ',
      vettingDashboard: 'ਉੱਦਮੀ ਸਮੀਖਿਆ',
      productModeration: 'ਉਤਪਾਦ ਸਮੀਖਿਆ',
      platformOverview: 'ਮੰਚ ਅਵਲੋਕਨ',
      pendingApproval: 'ਮਨਜ਼ੂਰੀ ਲੰਬਿਤ',
      approved: 'ਮਨਜ਼ੂਰਸ਼ੁਦਾ',
      suspended: 'ਮੁਅੱਤਲ',
      yourConversations: 'ਤੁਹਾਡੀਆਂ ਗੱਲਬਾਤਾਂ',
      yourOrders: 'ਤੁਹਾਡੇ ਆਰਡਰ',
      orders: 'ਆਰਡਰ',
      securitySettings: 'ਸੁਰੱਖਿਆ ਅਤੇ ਪਾਸਵਰਡ',
      currentPassword: 'ਮੌਜੂਦਾ ਪਾਸਵਰਡ',
      newPassword: 'ਨਵਾਂ ਪਾਸਵਰਡ',
      confirmPassword: 'ਨਵੇਂ ਪਾਸਵਰਡ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
      updatePassword: 'ਪਾਸਵਰਡ ਅੱਪਡੇਟ ਕਰੋ',
      profileUpdated: 'ਪ੍ਰੋਫਾਈਲ ਸਫਲਤਾਪੂਰਵਕ ਅੱਪਡੇਟ ਹੋ ਗਈ!',
      passwordUpdated: 'ਪਾਸਵਰਡ ਸਫਲਤਾਪੂਰਵਕ ਅੱਪਡੇਟ ਹੋ ਗਿਆ!',
      passwordMismatch: 'ਨਵੇਂ ਪਾਸਵਰਡ ਮੇਲ ਨਹੀਂ ਖਾਂਦੇ!',
      remove: 'ਹਟਾਓ',
      emptyWishlist: 'ਤੁਹਾਡੀ ਪਸੰਦੀਦਾ ਉਤਪਾਦ ਸੂਚੀ ਖਾਲੀ ਹੈ।',
      wishlistTitle: 'ਤੁਹਾਡੇ ਪਸੰਦੀਦਾ ਉਤਪਾਦ',
      wishlistSubtitle: 'ਹਸਤਕਲਾ ਵਸਤੂਆਂ ਦੀ ਆਪਣੀ ਆਦਰਸ਼ ਸੂਚੀ ਬਣਾਓ।',
      goFindFavorites: 'ਪਸੰਦੀਦਾ ਉਤਪਾਦ ਲੱਭੋ',
      buyerProfile: 'ਖਰੀਦਦਾਰ ਪ੍ਰੋਫਾਈਲ',
      sellerProfile: 'ਵਿਕਰੇਤਾ ਪ੍ਰੋਫਾਈਲ',
      adminProfile: 'ਐਡਮਿਨ ਪ੍ਰੋਫਾਈਲ',
      hello: 'ਸਤਿ ਸ਼੍ਰੀ ਅਕਾਲ',
      welcomeDashboard: 'ਆਪਣੇ ਕੰਟਰੋਲ ਪੈਨਲ ਵਿੱਚ ਜੀ ਆਇਆਂ ਨੂੰ।',
      totalPurchases: 'ਕੁੱਲ ਖਰੀਦਦਾਰੀ',
      savedFavorites: 'ਪਸੰਦੀਦਾ ਉਤਪਾਦ',
      recentTransactions: 'ਹਾਲੀਆ ਲੈਣ-ਦੇਣ',
      trackOrder: 'ਆਰਡਰ ਟਰੈਕ ਕਰੋ',
      noTransactions: 'ਕੋਈ ਲੈਣ-ਦੇਣ ਦਾ ਰਿਕਾਰਡ ਨਹੀਂ ਮਿਲਿਆ।',
      placedDate: 'ਮਿਤੀ',
      priceTotal: 'ਕੁੱਲ ਕੀਮਤ',
      shipStatus: 'ਸ਼ਿਪਮੈਂਟ ਸਥਿਤੀ',
      actions: 'ਕਾਰਵਾਈਆਂ',
      notifications: 'ਸੂਚਨਾਵਾਂ',
      markAllRead: 'ਸਭ ਨੂੰ ਪੜ੍ਹਿਆ ਹੋਇਆ ਨਿਸ਼ਾਨਬੱਧ ਕਰੋ',
      noNotifications: 'ਕੋਈ ਸੂਚਨਾ ਨਹੀਂ',
      workspace: 'ਵਰਕਸਪੇਸ',
      shipments: 'ਸ਼ਿਪਮੈਂਟਾਂ',
      profile: 'ਪ੍ਰੋਫਾਈਲ',
      filters: 'ਫਿਲਟਰ',
      productDetails: 'ਉਤਪਾਦ ਵੇਰਵੇ',
      viewDetails: 'ਵੇਰਵੇ ਵੇਖੋ',
      search: 'ਖੋਜ',
      category: 'ਸ਼੍ਰੇਣੀ',
      priceRange: 'ਕੀਮਤ ਸੀਮਾ',
      min: 'ਘੱਟੋ-ਘੱਟ',
      max: 'ਵੱਧ ਤੋਂ ਵੱਧ',
      status: 'ਸਥਿਤੀ',
      allStatuses: 'ਸਾਰੀਆਂ ਸਥਿਤੀਆਂ',
      dateRange: 'ਮਿਤੀ ਸੀਮਾ',
      sortOptions: 'ਤਰਤੀਬ',
      clearFilters: 'ਫਿਲਟਰ ਹਟਾਓ',
      filterSortOptions: 'ਫਿਲਟਰ ਅਤੇ ਤਰਤੀਬ',
      filterProducts: 'ਉਤਪਾਦ ਫਿਲਟਰ ਕਰੋ',
      applyFilters: 'ਫਿਲਟਰ ਲਾਗੂ ਕਰੋ',
      back: 'ਵਾਪਸ',
      by: 'ਦੁਆਰਾ',
      off: 'ਛੋਟ',
      total: 'ਕੁੱਲ',
      items: 'ਵਸਤੂਆਂ',
      price: 'ਕੀਮਤ',
      subtotal: 'ਉਪ-ਕੁੱਲ',
      gst: 'ਜੀਐਸਟੀ (5%)',
      grandTotal: 'ਕੁੱਲ ਦੇਣਯੋਗ',
      placeOrder: 'ਆਰਡਰ ਕਰੋ',
      shippingAddress: 'ਸ਼ਿਪਿੰਗ ਪਤਾ',
      trackingNumber: 'ਟਰੈਕਿੰਗ ਨੰਬਰ',
      deliveryAddress: 'ਡਿਲਿਵਰੀ ਪਤਾ',
      myProducts: 'ਮੇਰੇ ਉਤਪਾਦ',
      myCustomers: 'ਮੇਰੇ ਗਾਹਕ',
      salesAnalytics: 'ਬਿਕਰੀ ਵਿਸ਼ਲੇਸ਼ਣ',
      salesRevenue: 'ਬਿਕਰੀ ਆਮਦਨ',
      activeListings: 'ਸਰਗਰਮ ਉਤਪਾਦ',
      ordersFulfilled: 'ਪੂਰੇ ਕੀਤੇ ਆਰਡਰ',
      averageRating: 'ਔਸਤ ਰੇਟਿੰਗ',
      stockStatus: 'ਸਟਾਕ ਸਥਿਤੀ',
      inStock: 'ਸਟਾਕ ਵਿੱਚ ਉਪਲਬਧ',
      outOfStock: 'ਸਟਾਕ ਖਤਮ',
      lowStock: 'ਘੱਟ ਸਟਾਕ',
    },
  };

  // Smart i18n Translation Resolver with Automatic String Normalization
  const t = (key, fallback) => {
    if (!key) return '';
    const langDict = translations[language] || translations['en'] || {};
    if (langDict[key]) return langDict[key];

    // Try camelCase matching for raw UI string literals
    const camelKey = key.toString().replace(/(?:^\w|[A-Z]|\b\w)/g, (letter, index) =>
      index === 0 ? letter.toLowerCase() : letter.toUpperCase()
    ).replace(/[^a-zA-Z0-9]/g, '');

    if (langDict[camelKey]) return langDict[camelKey];

    const enDict = translations['en'] || {};
    if (enDict[key]) return enDict[key];
    if (enDict[camelKey]) return enDict[camelKey];

    return fallback !== undefined ? fallback : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export default LanguageProvider;
